# Generated by Django 5.2.15 on 2026-07-04 22:59

import apps.quotes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(editable=False, unique=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("sent", "Enviado"),
                            ("viewed", "Visualizado"),
                            ("approved", "Aprovado"),
                            ("rejected", "Recusado"),
                            ("expired", "Expirado"),
                            ("canceled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("customer_report", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("discount_type", models.CharField(default="none", max_length=10)),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "public_token",
                    models.CharField(
                        default=apps.quotes.models.generate_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_to_email", models.EmailField(blank=True, max_length=254)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approval_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("physical", "Assinatura física"),
                            ("tablet", "Assinatura no tablet"),
                            ("email_link", "Link por e-mail"),
                        ],
                        max_length=20,
                    ),
                ),
                ("client_name", models.CharField(blank=True, max_length=200)),
                ("terms_accepted", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True)),
                ("decision_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("decision_user_agent", models.TextField(blank=True)),
                ("approval_note", models.TextField(blank=True)),
                (
                    "signature_image",
                    models.FileField(
                        blank=True, null=True, upload_to="quotes/signatures/"
                    ),
                ),
                (
                    "signed_document",
                    models.FileField(blank=True, null=True, upload_to="quotes/signed/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="orders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service", "Serviço"),
                            ("package", "Pacote"),
                            ("part", "Peça"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_custom", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotes.quote",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
