# Generated by Django 5.2.15 on 2026-07-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("approved", "Aprovado"),
                    ("rejected", "Recusado"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("sent", "Enviado"),
                    ("viewed", "Visualizado"),
                    ("partially_approved", "Aprovado parcialmente"),
                    ("approved", "Aprovado integralmente"),
                    ("rejected", "Recusado"),
                    ("expired", "Expirado"),
                    ("canceled", "Cancelado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
