# Generated by Django 5.2.15 on 2026-07-05 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_quoteitem_status_alter_quote_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteitem",
            name="linked_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_parts",
                to="quotes.quoteitem",
            ),
        ),
    ]
