# Generated by Django 5.2.16 on 2026-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_quoteitem_linked_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("sent", "Enviado"),
                    ("viewed", "Visualizado"),
                    ("partially_approved", "Aprovado parcialmente"),
                    ("approved", "Aprovado integralmente"),
                    ("rejected", "Recusado"),
                    ("expired", "Expirado"),
                    ("canceled", "Cancelado"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
