# Generated by Django 5.2.16 on 2026-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_alter_quote_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteitem",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="part_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Padrão do serviço"),
                    ("manual", "Avulsa associada"),
                    ("independent", "Avulsa independente"),
                ],
                default="",
                max_length=12,
            ),
        ),
    ]
