# Generated by Django 5.2.16 on 2026-07-12 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_workorderpart_is_required"),
        ("smart_search", "0002_unaccent"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartsearchsettings",
            name="embedding_api_key_env",
            field=models.CharField(
                default="SMART_SEARCH_EMBEDDING_KEY", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="smartsearchsettings",
            name="embedding_base_url",
            field=models.CharField(default="https://api.openai.com/v1", max_length=300),
        ),
        migrations.AddField(
            model_name="smartsearchsettings",
            name="embedding_dimensions",
            field=models.PositiveSmallIntegerField(default=512),
        ),
        migrations.AddField(
            model_name="smartsearchsettings",
            name="embedding_model",
            field=models.CharField(default="text-embedding-3-small", max_length=100),
        ),
        migrations.AddField(
            model_name="smartsearchsettings",
            name="embedding_provider",
            field=models.CharField(default="openai", max_length=20),
        ),
        migrations.AddField(
            model_name="smartsearchsettings",
            name="semantic_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="smartsearchsettings",
            name="similarity_threshold",
            field=models.FloatField(default=0.78),
        ),
        migrations.CreateModel(
            name="WorkOrderEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", models.JSONField(default=list)),
                ("source_hash", models.CharField(db_index=True, max_length=64)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_embedding",
                        to="orders.workorder",
                    ),
                ),
            ],
        ),
    ]
