# Generated by Django 5.2.15 on 2026-07-08 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0007_alter_orderevent_event_type"),
        ("quotes", "0003_quoteitem_linked_service"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("order_opened", "Abertura de ordem de serviço"),
                            ("appointment_confirmed", "Confirmação de agendamento"),
                            ("no_show", "Cliente não compareceu"),
                            ("vehicle_checkin", "Check-in do veículo"),
                            ("diagnosis_done", "Diagnóstico concluído"),
                            ("quote_sent", "Orçamento enviado"),
                            ("quote_approved", "Orçamento aprovado totalmente"),
                            (
                                "quote_partially_approved",
                                "Orçamento aprovado parcialmente",
                            ),
                            ("quote_rejected", "Orçamento recusado"),
                            ("awaiting_parts", "OS aguardando peças"),
                            ("in_progress", "OS em execução"),
                            ("in_testing", "OS em teste"),
                            ("ready_for_pickup", "OS pronta para retirada"),
                            ("os_finished", "OS finalizada"),
                            ("financial_pending", "Cobrança ou pendência financeira"),
                            ("pickup_reminder", "Lembrete de retirada do veículo"),
                            ("post_service_followup", "Follow-up pós-serviço"),
                            ("manual_general", "Mensagem geral (envio manual)"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "E-mail"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("internal", "Notificação interna"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("html_content", models.TextField(blank=True)),
                ("text_content", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_customized", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_templates_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["event", "channel"],
                "unique_together": {("event", "channel")},
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=40)),
                ("channel", models.CharField(max_length=20)),
                ("recipient", models.CharField(blank=True, max_length=200)),
                ("subject", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Enviado"),
                            ("failed", "Falhou"),
                            ("skipped", "Ignorado"),
                        ],
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("is_test", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="quotes.quote",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="orders.workorder",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
