# Generated by Django 5.2.15 on 2026-07-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_seed_payment_received"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtemplate",
            name="event",
            field=models.CharField(
                choices=[
                    ("order_opened", "Abertura de ordem de serviço"),
                    ("appointment_confirmed", "Confirmação de agendamento"),
                    ("no_show", "Cliente não compareceu"),
                    ("vehicle_checkin", "Check-in do veículo"),
                    ("diagnosis_done", "Diagnóstico concluído"),
                    ("quote_sent", "Orçamento enviado"),
                    ("quote_approved", "Orçamento aprovado totalmente"),
                    ("quote_partially_approved", "Orçamento aprovado parcialmente"),
                    ("quote_rejected", "Orçamento recusado"),
                    ("awaiting_parts", "OS aguardando peças"),
                    ("in_progress", "OS em execução"),
                    ("in_testing", "OS em teste"),
                    ("ready_for_pickup", "OS pronta para retirada"),
                    ("os_finished", "OS finalizada"),
                    ("financial_pending", "Cobrança ou pendência financeira"),
                    ("payment_received", "Pagamento recebido (recibo)"),
                    ("pickup_reminder", "Lembrete de retirada do veículo"),
                    ("post_service_followup", "Follow-up pós-serviço"),
                    ("manual_general", "Mensagem geral (envio manual)"),
                ],
                max_length=40,
            ),
        ),
    ]
