# Generated by Django 5.2.15 on 2026-07-08 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0007_alter_orderevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFieldInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_key",
                    models.CharField(
                        choices=[
                            ("customer_report", "Relato do cliente"),
                            ("diagnosis", "Diagnóstico técnico"),
                            ("internal_notes", "Observações internas"),
                            ("procedures", "Procedimentos realizados"),
                            ("recommendations", "Recomendações técnicas"),
                            ("customer_notes", "Observações para o cliente"),
                            ("os_summary", "Resumo da OS"),
                            ("quote_text", "Texto para orçamento"),
                            ("approval_text", "Texto para aprovação do cliente"),
                            ("finalization_text", "Texto para finalização da OS"),
                            ("pdf_text", "Texto para PDF/ordem impressa"),
                            ("message_text", "Comunicação por WhatsApp/e-mail"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("instruction", models.TextField()),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("objective", "Objetivo"),
                            ("technical", "Técnico"),
                            ("commercial", "Comercial"),
                            ("friendly", "Amigável"),
                            ("formal", "Formal"),
                        ],
                        default="objective",
                        max_length=20,
                    ),
                ),
                (
                    "detail_level",
                    models.CharField(
                        choices=[
                            ("concise", "Conciso"),
                            ("normal", "Equilibrado"),
                            ("detailed", "Detalhado"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("customer", "Cliente"),
                            ("mechanic", "Mecânico"),
                            ("attendant", "Atendente"),
                            ("manager", "Gerente"),
                            ("internal", "Uso interno"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("can_rewrite", models.BooleanField(default=True)),
                ("can_fix_grammar", models.BooleanField(default=True)),
                ("can_summarize", models.BooleanField(default=True)),
                ("can_expand", models.BooleanField(default=True)),
                ("use_context", models.BooleanField(default=True)),
                ("allowed_context", models.JSONField(blank=True, default=list)),
                ("preserve_technical_terms", models.BooleanField(default=True)),
                ("keep_first_person", models.BooleanField(default=False)),
                ("remove_slang", models.BooleanField(default=True)),
                ("visible_to_customer", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_customized", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_field_instructions_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["field_key"],
            },
        ),
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("anthropic", "Anthropic (Claude)"),
                            ("openai", "OpenAI"),
                            ("gemini", "Gemini"),
                            ("custom", "Outro (compatível OpenAI)"),
                        ],
                        default="anthropic",
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(default="claude-opus-4-8", max_length=80)),
                ("base_url", models.CharField(blank=True, max_length=300)),
                ("api_key_env", models.CharField(blank=True, max_length=80)),
                ("temperature", models.FloatField(default=0.3)),
                ("max_tokens", models.PositiveIntegerField(default=1200)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                (
                    "global_prompt",
                    models.TextField(
                        default="Você é um assistente de escrita para uma oficina mecânica. Sua função é ajudar a redigir, revisar, padronizar e melhorar textos da Ordem de Serviço (OS). Você NÃO é uma fonte autônoma de informação técnica.\n\nRegras invioláveis:\n- Nunca invente informações. Se o texto original não tiver dados suficientes, apenas melhore a clareza do que foi informado ou indique que faltam informações.\n- Nunca crie sintomas, defeitos, causas, peças, serviços, testes, medições, valores, prazos, aprovações ou procedimentos que não tenham sido informados.\n- Nunca assuma que uma peça foi trocada ou que um serviço foi autorizado se isso não estiver explícito.\n- Nunca altere placa, nome do cliente, modelo do veículo, número da OS ou valores.\n- Nunca altere dados técnicos sensíveis fornecidos pelo mecânico.\n- Use linguagem profissional, clara e adequada para oficina mecânica.\n- Diferencie texto interno de texto visível ao cliente.\n- Responda no idioma do texto original (padrão: português do Brasil).\n- Retorne APENAS o texto final do campo, sem explicações adicionais, aspas ou comentários, salvo quando a ação pedir explicitamente uma análise.\n- A sugestão será revisada por um responsável da oficina antes de ser aplicada."
                    ),
                ),
                ("log_texts", models.BooleanField(default=False)),
                ("retention_days", models.PositiveIntegerField(default=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_settings_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_key", models.CharField(max_length=40)),
                ("action", models.CharField(max_length=40)),
                ("provider", models.CharField(max_length=20)),
                ("model", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Sucesso"), ("failed", "Falhou")],
                        max_length=10,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=40)),
                ("error", models.TextField(blank=True)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("is_test", models.BooleanField(default=False)),
                ("applied", models.BooleanField(blank=True, null=True)),
                ("input_text", models.TextField(blank=True)),
                ("output_text", models.TextField(blank=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to="orders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
