# Generated by Django 5.2.16 on 2026-07-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_seed_field_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aisettings",
            name="model",
            field=models.CharField(default="gpt-4o-mini", max_length=80),
        ),
        migrations.AlterField(
            model_name="aisettings",
            name="provider",
            field=models.CharField(
                choices=[
                    ("anthropic", "Anthropic (Claude)"),
                    ("openai", "OpenAI"),
                    ("gemini", "Gemini"),
                    ("custom", "Outro (compatível OpenAI)"),
                ],
                default="openai",
                max_length=20,
            ),
        ),
    ]
