# Generated by Django 5.2.16 on 2026-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepart",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="servicepart",
            name="notes",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
