# Generated by Django 5.2.16 on 2026-07-09 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0009_resync_rbac_alerts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("muted_modules", models.JSONField(blank=True, default=list)),
                ("only_assigned", models.BooleanField(default=False)),
                ("only_high_priority", models.BooleanField(default=False)),
                ("mute_informational", models.BooleanField(default=False)),
                ("sound_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_pref",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("site_lead_created", "Novo pedido do site"),
                            ("site_lead_sla", "Pedido do site aguardando contato"),
                            ("os_due_soon", "OS próxima do vencimento"),
                            ("os_overdue", "OS atrasada"),
                            ("os_stalled", "OS parada no mesmo status"),
                            ("quote_pending", "Orçamento aguardando resposta"),
                            ("quote_approved", "Orçamento aprovado"),
                            ("quote_rejected", "Orçamento recusado"),
                            ("payments_today", "Pagamentos registrados hoje"),
                            ("payments_pending", "OS com pagamento pendente"),
                            ("stock_low", "Estoque abaixo do mínimo"),
                            ("manual", "Aviso manual"),
                            ("admin", "Aviso administrativo"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("info", "Informativa"),
                            ("attention", "Atenção"),
                            ("important", "Importante"),
                            ("urgent", "Urgente"),
                            ("critical", "Crítica"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lead_time_hours", models.PositiveIntegerField(default=24)),
                ("stall_days", models.PositiveIntegerField(default=2)),
                ("recipient_roles", models.JSONField(blank=True, default=list)),
                ("show_in_bell", models.BooleanField(default=True)),
                ("send_email", models.BooleanField(default=False)),
                ("show_in_dashboard", models.BooleanField(default=False)),
                ("group_similar", models.BooleanField(default=False)),
                ("auto_expire_days", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["notif_type"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("site_lead_created", "Novo pedido do site"),
                            ("site_lead_sla", "Pedido do site aguardando contato"),
                            ("os_due_soon", "OS próxima do vencimento"),
                            ("os_overdue", "OS atrasada"),
                            ("os_stalled", "OS parada no mesmo status"),
                            ("quote_pending", "Orçamento aguardando resposta"),
                            ("quote_approved", "Orçamento aprovado"),
                            ("quote_rejected", "Orçamento recusado"),
                            ("payments_today", "Pagamentos registrados hoje"),
                            ("payments_pending", "OS com pagamento pendente"),
                            ("stock_low", "Estoque abaixo do mínimo"),
                            ("manual", "Aviso manual"),
                            ("admin", "Aviso administrativo"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("leads", "Site/Pedidos"),
                            ("orders", "Ordem de Serviço"),
                            ("quotes", "Orçamentos"),
                            ("financial", "Financeiro"),
                            ("parts", "Estoque"),
                            ("system", "Sistema"),
                            ("admin", "Administrativo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.CharField(max_length=500)),
                ("detail", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("info", "Informativa"),
                            ("attention", "Atenção"),
                            ("important", "Importante"),
                            ("urgent", "Urgente"),
                            ("critical", "Crítica"),
                        ],
                        default="important",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Não lida"),
                            ("read", "Lida"),
                            ("archived", "Arquivada"),
                        ],
                        default="unread",
                        max_length=20,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("related_type", models.CharField(blank=True, max_length=60)),
                ("related_id", models.PositiveIntegerField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=300)),
                ("action_label", models.CharField(blank=True, max_length=80)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("automatic", "Automática"),
                            ("manual", "Manual"),
                            ("system", "Sistema"),
                        ],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audience_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.role",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"],
                        name="alerts_noti_recipie_58fc7d_idx",
                    ),
                    models.Index(
                        fields=["recipient", "module"],
                        name="alerts_noti_recipie_b44497_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedup_key", ""), _negated=True),
                        fields=("recipient", "dedup_key"),
                        name="uniq_recipient_dedup_key",
                    )
                ],
            },
        ),
    ]
