# Generated by Django 5.2.16 on 2026-07-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="module",
            field=models.CharField(
                choices=[
                    ("leads", "Site/Pedidos"),
                    ("orders", "Ordem de Serviço"),
                    ("quotes", "Orçamentos"),
                    ("financial", "Financeiro"),
                    ("parts", "Estoque"),
                    ("crm", "CRM inteligente"),
                    ("system", "Sistema"),
                    ("admin", "Administrativo"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("site_lead_created", "Novo pedido do site"),
                    ("site_lead_sla", "Pedido do site aguardando contato"),
                    ("os_due_soon", "OS próxima do vencimento"),
                    ("os_overdue", "OS atrasada"),
                    ("os_stalled", "OS parada no mesmo status"),
                    ("quote_pending", "Orçamento aguardando resposta"),
                    ("quote_approved", "Orçamento aprovado"),
                    ("quote_rejected", "Orçamento recusado"),
                    ("payments_today", "Pagamentos registrados hoje"),
                    ("payments_pending", "OS com pagamento pendente"),
                    ("stock_low", "Estoque abaixo do mínimo"),
                    ("crm_suggestion", "Sugestão do CRM inteligente"),
                    ("manual", "Aviso manual"),
                    ("admin", "Aviso administrativo"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("site_lead_created", "Novo pedido do site"),
                    ("site_lead_sla", "Pedido do site aguardando contato"),
                    ("os_due_soon", "OS próxima do vencimento"),
                    ("os_overdue", "OS atrasada"),
                    ("os_stalled", "OS parada no mesmo status"),
                    ("quote_pending", "Orçamento aguardando resposta"),
                    ("quote_approved", "Orçamento aprovado"),
                    ("quote_rejected", "Orçamento recusado"),
                    ("payments_today", "Pagamentos registrados hoje"),
                    ("payments_pending", "OS com pagamento pendente"),
                    ("stock_low", "Estoque abaixo do mínimo"),
                    ("crm_suggestion", "Sugestão do CRM inteligente"),
                    ("manual", "Aviso manual"),
                    ("admin", "Aviso administrativo"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
