# Generated by Django 5.2.16 on 2026-07-09 18:04

import apps.checkin.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0008_alter_workorder_is_active_alter_workorder_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "Em andamento"),
                            ("completed", "Concluído"),
                            ("reviewed", "Revisado"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("mileage", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fuel_level",
                    models.CharField(
                        choices=[
                            ("not_checked", "Não verificado"),
                            ("reserve", "Reserva"),
                            ("quarter", "1/4"),
                            ("half", "1/2"),
                            ("three_quarters", "3/4"),
                            ("full", "Cheio"),
                        ],
                        default="not_checked",
                        max_length=20,
                    ),
                ),
                ("external_condition", models.CharField(blank=True, max_length=200)),
                ("internal_condition", models.CharField(blank=True, max_length=200)),
                ("general_notes", models.TextField(blank=True)),
                ("arrived_driving", models.BooleanField(default=True)),
                ("arrived_towed", models.BooleanField(default=False)),
                ("customer_present", models.BooleanField(default=False)),
                ("customer_confirmed", models.BooleanField(default=False)),
                (
                    "belongings_status",
                    models.CharField(
                        choices=[
                            ("yes", "Sim"),
                            ("no", "Não"),
                            ("not_verified", "Não verificado"),
                        ],
                        default="not_verified",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in",
                        to="orders.workorder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleCheckInBelonging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.checkin.models.belonging_photo_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belongings",
                        to="checkin.vehiclecheckin",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="VehicleCheckInItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Presente"),
                            ("absent", "Ausente"),
                            ("na", "Não se aplica"),
                            ("unchecked", "Não verificado"),
                        ],
                        default="unchecked",
                        max_length=12,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="checkin.vehiclecheckin",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="VehicleCheckInPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("front", "Frente"),
                            ("rear", "Traseira"),
                            ("left", "Lateral esquerda"),
                            ("right", "Lateral direita"),
                            ("interior", "Interior"),
                            ("dashboard", "Painel"),
                            ("trunk", "Porta-malas"),
                            ("engine", "Motor"),
                            ("odometer", "Quilometragem/painel"),
                            ("document", "Documento/placa"),
                            ("other", "Outras"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=apps.checkin.models.checkin_photo_path),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="checkin.vehiclecheckin",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VehicleDamage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.DecimalField(decimal_places=2, max_digits=5)),
                ("y", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("front", "Frente"),
                            ("hood", "Capô"),
                            ("windshield", "Para-brisa"),
                            ("roof", "Teto"),
                            ("front_left_door", "Porta dianteira esquerda"),
                            ("rear_left_door", "Porta traseira esquerda"),
                            ("left_side", "Lateral esquerda"),
                            ("front_right_door", "Porta dianteira direita"),
                            ("rear_right_door", "Porta traseira direita"),
                            ("right_side", "Lateral direita"),
                            ("trunk", "Porta-malas"),
                            ("front_bumper", "Para-choque dianteiro"),
                            ("rear_bumper", "Para-choque traseiro"),
                            ("wheels", "Rodas"),
                            ("mirrors", "Retrovisores"),
                            ("headlights", "Faróis"),
                            ("taillights", "Lanternas"),
                            ("interior", "Interior"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=24,
                    ),
                ),
                (
                    "damage_type",
                    models.CharField(
                        choices=[
                            ("scratch", "Risco"),
                            ("dent", "Amassado"),
                            ("broken", "Quebrado"),
                            ("cracked", "Trincado"),
                            ("missing_part", "Peça faltando"),
                            ("paint", "Pintura danificada"),
                            ("glass", "Vidro danificado"),
                            ("light", "Farol/lanterna danificado"),
                            ("tire", "Pneu/roda danificado"),
                            ("mirror", "Retrovisor danificado"),
                            ("interior", "Interior danificado"),
                            ("stain", "Sujeira/mancha"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("light", "Leve"),
                            ("medium", "Média"),
                            ("severe", "Grave"),
                        ],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("internal_notes", models.TextField(blank=True)),
                ("visible_to_customer", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damages",
                        to="checkin.vehiclecheckin",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="VehicleDamagePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=apps.checkin.models.damage_photo_path),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "damage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="checkin.vehicledamage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
