# Generated by Django 5.2.15 on 2026-07-07 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0006_alter_orderevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Dinheiro"),
                            ("pix", "Pix"),
                            ("debit", "Cartão de débito"),
                            ("credit", "Cartão de crédito"),
                            ("transfer", "Transferência"),
                            ("boleto", "Boleto"),
                            ("other", "Outro"),
                        ],
                        default="pix",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateField()),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-id"],
            },
        ),
    ]
