# Generated by Django 5.2.15 on 2026-07-07 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("suppliers", "Fornecedores/Peças"),
                            ("salaries", "Salários/Mão de obra"),
                            ("rent", "Aluguel"),
                            ("utilities", "Água/Luz/Internet"),
                            ("taxes", "Impostos/Taxas"),
                            ("marketing", "Marketing"),
                            ("maintenance", "Manutenção/Equipamentos"),
                            ("other", "Outras"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Dinheiro"),
                            ("pix", "Pix"),
                            ("debit", "Cartão de débito"),
                            ("credit", "Cartão de crédito"),
                            ("transfer", "Transferência"),
                            ("boleto", "Boleto"),
                            ("other", "Outro"),
                        ],
                        default="pix",
                        max_length=20,
                    ),
                ),
                ("incurred_at", models.DateField()),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-incurred_at", "-id"],
            },
        ),
    ]
