# Generated by Django 5.2.16 on 2026-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0002_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_at",
            field=models.DateField(db_index=True),
        ),
    ]
