# Generated by Django 5.2.15 on 2026-07-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_workorderpart_linked_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="stock_deducted",
            field=models.BooleanField(default=False),
        ),
    ]
