# Generated by Django 5.2.15 on 2026-07-06 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_workorder_assigned_technician_orderattachment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderattachment",
            name="caption",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="orderattachment",
            name="category",
            field=models.CharField(
                choices=[
                    ("entry", "Entrada do veículo"),
                    ("external_damage", "Avaria externa"),
                    ("internal_damage", "Avaria interna"),
                    ("engine", "Motor"),
                    ("suspension", "Suspensão"),
                    ("brakes", "Freios"),
                    ("damaged_part", "Peça danificada"),
                    ("in_progress", "Serviço em andamento"),
                    ("completed", "Serviço concluído"),
                    ("delivery", "Entrega do veículo"),
                    ("other", "Outros"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "OS criada"),
                            ("status_changed", "Status alterado"),
                            ("attachment_added", "Foto/anexo adicionado"),
                            ("attachment_removed", "Foto/anexo removido"),
                            ("quote_created", "Orçamento criado"),
                            ("quote_sent", "Orçamento enviado"),
                            ("quote_approved", "Orçamento aprovado"),
                            (
                                "quote_partially_approved",
                                "Orçamento aprovado parcialmente",
                            ),
                            ("quote_rejected", "Orçamento recusado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("channel", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
