# Generated by Django 5.2.15 on 2026-07-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_orderevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "OS criada"),
                    ("status_changed", "Status alterado"),
                    ("attachment_added", "Foto/anexo adicionado"),
                    ("attachment_removed", "Foto/anexo removido"),
                    ("quote_created", "Orçamento criado"),
                    ("quote_sent", "Orçamento enviado"),
                    ("quote_approved", "Orçamento aprovado"),
                    ("quote_partially_approved", "Orçamento aprovado parcialmente"),
                    ("quote_rejected", "Orçamento recusado"),
                    ("payment_registered", "Pagamento registrado"),
                    ("payment_removed", "Pagamento estornado"),
                    ("customer_notified", "Cliente notificado por e-mail"),
                ],
                max_length=30,
            ),
        ),
    ]
