# Generated by Django 5.2.16 on 2026-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_orderevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Aberta"),
                    ("diagnosing", "Em diagnóstico"),
                    ("awaiting_approval", "Aguardando aprovação"),
                    ("approved", "Aprovada"),
                    ("in_progress", "Em execução"),
                    ("awaiting_parts", "Aguardando peças"),
                    ("testing", "Em teste"),
                    ("ready", "Pronta para entrega"),
                    ("finished", "Finalizada"),
                    ("canceled", "Cancelada"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
