# Generated by Django 5.2.16 on 2026-07-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_workorder_is_active_alter_workorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatushistory",
            name="action",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="reason",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("system", "Sistema"),
                    ("approval", "Aprovação de orçamento"),
                    ("stock", "Estoque"),
                    ("financial", "Financeiro"),
                    ("integration", "Integração"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Aberta"),
                    ("diagnosing", "Em diagnóstico"),
                    ("awaiting_approval", "Aguardando aprovação"),
                    ("approved", "Aprovada"),
                    ("in_progress", "Em execução"),
                    ("awaiting_parts", "Aguardando peças"),
                    ("testing", "Em teste"),
                    ("ready", "Pronta para entrega"),
                    ("finished", "Finalizada"),
                    ("canceled", "Cancelada"),
                    ("rejected", "Recusada"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
