# Generated by Django 5.2.16 on 2026-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_orderstatushistory_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderpart",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
