# Generated by Django 5.2.16 on 2026-07-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_workorderpart_is_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="payment_due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
