# Generated by Django 5.2.15 on 2026-07-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_delivery_days", models.PositiveIntegerField(default=7)),
                (
                    "warranty_terms",
                    models.TextField(
                        blank=True,
                        default="Os serviços executados possuem garantia de 90 (noventa) dias a partir da data de entrega do veículo, cobrindo exclusivamente os itens descritos nesta ordem de serviço. A garantia não cobre desgaste natural, mau uso ou intervenções realizadas por terceiros.",
                    ),
                ),
                (
                    "quote_terms",
                    models.TextField(
                        blank=True,
                        default="Este orçamento tem validade de 7 (sete) dias. Os valores podem ser revistos caso sejam identificados serviços ou peças adicionais durante a execução, sempre mediante nova aprovação do cliente.",
                    ),
                ),
                (
                    "service_authorization_terms",
                    models.TextField(
                        blank=True,
                        default="Autorizo a execução dos serviços descritos nesta ordem de serviço, bem como a utilização das peças relacionadas, declarando estar ciente dos valores e prazos informados.",
                    ),
                ),
                (
                    "customer_acknowledgment_terms",
                    models.TextField(
                        blank=True,
                        default="Declaro que retirei o veículo em perfeito estado de funcionamento, ciente dos serviços realizados e das condições de garantia aplicáveis.",
                    ),
                ),
                ("default_os_notes", models.TextField(blank=True)),
                (
                    "pdf_footer_text",
                    models.TextField(
                        blank=True,
                        default="Documento gerado eletronicamente pelo sistema DriverOps.",
                    ),
                ),
                ("print_instructions", models.TextField(blank=True)),
                ("general_conditions", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkshopProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_name", models.CharField(blank=True, max_length=150)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("cnpj", models.CharField(blank=True, max_length=14)),
                ("state_registration", models.CharField(blank=True, max_length=20)),
                ("responsible", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=11)),
                ("whatsapp", models.CharField(blank=True, max_length=11)),
                ("website", models.CharField(blank=True, max_length=200)),
                ("logo_url", models.URLField(blank=True)),
                ("zip_code", models.CharField(blank=True, max_length=8)),
                ("street", models.CharField(blank=True, max_length=200)),
                ("number", models.CharField(blank=True, max_length=20)),
                ("complement", models.CharField(blank=True, max_length=100)),
                ("neighborhood", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                (
                    "country",
                    models.CharField(blank=True, default="Brasil", max_length=60),
                ),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
