# Generated by Django 5.2.15 on 2026-07-04 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workshopprofile",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="workshopprofile",
            name="logo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="workshop/logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "webp", "gif"]
                    )
                ],
            ),
        ),
    ]
