# Generated by Django 5.2.15 on 2026-07-04 20:51

import apps.workshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0002_remove_workshopprofile_logo_url_workshopprofile_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="KanbanSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=apps.workshop.models.default_kanban_columns
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
