# Generated by Django 5.2.15 on 2026-07-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0003_kanbansettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersettings",
            name="notify_customer_by_email",
            field=models.BooleanField(default=True),
        ),
    ]
