# Generated by Django 5.2.15 on 2026-07-07 21:37

import apps.workshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0004_ordersettings_notify_customer_by_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersettings",
            name="notify_on_creation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordersettings",
            name="notify_on_payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordersettings",
            name="notify_statuses",
            field=models.JSONField(
                default=apps.workshop.models.default_notify_statuses
            ),
        ),
    ]
