# Generated by Django 5.2.15 on 2026-07-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0005_ordersettings_notify_on_creation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopprofile",
            name="business_hours",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
