# Generated by Django 5.2.16 on 2026-07-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0006_workshopprofile_business_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopprofile",
            name="testimonials",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
