# Generated by Django 5.2.16 on 2026-07-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0007_workshopprofile_testimonials"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersettings",
            name="require_approved_quote_for_execution",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordersettings",
            name="require_checkin_before_execution",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordersettings",
            name="require_diagnosis_before_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordersettings",
            name="require_payment_to_finish",
            field=models.BooleanField(default=False),
        ),
    ]
