# Generated by Django 5.2.16 on 2026-07-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workshop",
            "0008_ordersettings_require_approved_quote_for_execution_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersettings",
            name="default_payment_due_days",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
