# Generated by Django 5.2.16 on 2026-07-13 07:09

import apps.workshop.pdf_blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0009_ordersettings_default_payment_due_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="PdfLayoutSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blocks",
                    models.JSONField(
                        default=apps.workshop.pdf_blocks.default_pdf_blocks
                    ),
                ),
                ("accent_color", models.CharField(default="#e5e7eb", max_length=7)),
                ("base_font_size", models.FloatField(default=8.5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
