# Generated by Django 5.2.16 on 2026-07-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0010_pdflayoutsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersettings",
            name="pdf_client_copy_label",
            field=models.CharField(blank=True, default="VIA DO CLIENTE", max_length=60),
        ),
        migrations.AddField(
            model_name="ordersettings",
            name="pdf_signature_label",
            field=models.CharField(
                blank=True,
                default="Assinatura do cliente na retirada do veículo:",
                max_length=120,
            ),
        ),
    ]
