# Generated by Django 5.2.16 on 2026-07-11 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0004_customerinteraction"),
        ("vehicles", "0002_alter_vehicle_license_plate"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerPortalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("require_email", models.BooleanField(default=False)),
                ("link_validity_hours", models.PositiveIntegerField(default=5)),
                ("single_use_token", models.BooleanField(default=False)),
                ("resend_cooldown_seconds", models.PositiveIntegerField(default=300)),
                ("show_history", models.BooleanField(default=True)),
                ("allow_messages", models.BooleanField(default=True)),
                ("allow_pdf_download", models.BooleanField(default=True)),
                ("notify_on_access", models.BooleanField(default=False)),
                ("notify_on_message", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked", models.BooleanField(default=False)),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("request_user_agent", models.CharField(blank=True, max_length=300)),
                ("access_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("access_user_agent", models.CharField(blank=True, max_length=300)),
                ("access_count", models.PositiveIntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_tokens",
                        to="customers.customer",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_tokens",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("quote", "Dúvida sobre orçamento"),
                            ("progress", "Dúvida sobre andamento"),
                            ("callback", "Quero que me liguem"),
                            ("pickup", "Combinar retirada"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("preferred_time", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_messages",
                        to="customers.customer",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_messages",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="customer_portal.vehicleaccesstoken",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
