# Generated by Django 5.2.15 on 2026-07-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_customer_whatsapp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=7)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("version", models.CharField(blank=True, max_length=100)),
                (
                    "manufacture_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("model_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("mileage", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gasoline", "Gasolina"),
                            ("ethanol", "Etanol"),
                            ("flex", "Flex"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Híbrido"),
                            ("electric", "Elétrico"),
                            ("cng", "GNV"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Manual"),
                            ("automatic", "Automático"),
                            ("automated", "Automatizado"),
                            ("cvt", "CVT"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "steering",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mechanical", "Mecânica"),
                            ("hydraulic", "Hidráulica"),
                            ("electric", "Elétrica"),
                            ("electrohydraulic", "Eletro-hidráulica"),
                            ("other", "Outra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("doors", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("air_conditioning", models.BooleanField(blank=True, null=True)),
                ("is_modified", models.BooleanField(blank=True, null=True)),
                ("modification_notes", models.TextField(blank=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("car", "Carro"),
                            ("motorcycle", "Moto"),
                            ("pickup", "Caminhonete"),
                            ("van", "Van"),
                            ("truck", "Caminhão"),
                            ("utility", "Utilitário"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "usage_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("private", "Particular"),
                            ("commercial", "Comercial"),
                            ("ride_hailing", "Aplicativo"),
                            ("taxi", "Táxi"),
                            ("fleet", "Frota"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("chassis", models.CharField(blank=True, max_length=30)),
                ("renavam", models.CharField(blank=True, max_length=20)),
                ("fipe_code", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["license_plate"],
            },
        ),
    ]
