# Generated by Django 5.2.16 on 2026-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(db_index=True, max_length=7),
        ),
    ]
