# Generated by Django 5.2.16 on 2026-07-09 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_customer_whatsapp"),
        ("orders", "0007_alter_orderevent_event_type"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("email_required", models.BooleanField(default=False)),
                ("plate_required", models.BooleanField(default=True)),
                ("allow_without_vehicle", models.BooleanField(default=False)),
                ("require_consent", models.BooleanField(default=True)),
                ("sla_hours", models.PositiveIntegerField(default=2)),
                ("auto_reply_enabled", models.BooleanField(default=False)),
                ("notify_email", models.BooleanField(default=False)),
                ("allow_create_os", models.BooleanField(default=True)),
                ("allow_create_appointment", models.BooleanField(default=True)),
                ("require_review_on_divergence", models.BooleanField(default=True)),
                (
                    "block_conversion_when_vehicle_other_customer",
                    models.BooleanField(default=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_settings_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=11)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("document", models.CharField(blank=True, max_length=14)),
                ("vehicle_plate", models.CharField(blank=True, max_length=7)),
                ("vehicle_brand", models.CharField(blank=True, max_length=100)),
                ("vehicle_model", models.CharField(blank=True, max_length=100)),
                (
                    "vehicle_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("vehicle_mileage", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("diagnostic", "Diagnóstico"),
                            ("revision", "Revisão"),
                            ("quote", "Orçamento"),
                            ("preventive", "Manutenção preventiva"),
                            ("mechanical", "Problema mecânico"),
                            ("electrical", "Problema elétrico"),
                            ("brakes", "Freios"),
                            ("suspension", "Suspensão"),
                            ("ac", "Ar-condicionado"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "best_period",
                    models.CharField(
                        choices=[
                            ("morning", "Manhã"),
                            ("afternoon", "Tarde"),
                            ("evening", "Noite"),
                            ("any", "Qualquer horário"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("desired_date", models.DateField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
                ("consent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Novo"),
                            ("in_analysis", "Em análise"),
                            ("contacted", "Cliente contatado"),
                            ("awaiting_return", "Aguardando retorno"),
                            ("converted_customer", "Convertido em cliente"),
                            ("converted_appointment", "Convertido em agendamento"),
                            ("converted_os", "Convertido em OS"),
                            ("converted_quote", "Convertido em orçamento"),
                            ("duplicate", "Duplicado"),
                            ("no_success", "Sem sucesso"),
                            ("canceled", "Cancelado"),
                        ],
                        default="new",
                        max_length=24,
                    ),
                ),
                ("source", models.CharField(default="site", max_length=20)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_leads",
                        to="customers.customer",
                    ),
                ),
                (
                    "linked_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_leads",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_leads",
                        to="orders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Pedido criado"),
                            ("status", "Status alterado"),
                            ("assign", "Responsável alterado"),
                            ("note", "Observação interna"),
                            ("contact", "Contato registrado"),
                            ("link_customer", "Cliente vinculado"),
                            ("create_customer", "Cliente criado"),
                            ("link_vehicle", "Veículo vinculado"),
                            ("create_vehicle", "Veículo criado"),
                            ("convert_os", "OS gerada"),
                            ("convert_quote", "Orçamento gerado"),
                            ("notify", "Notificação enviada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("from_status", models.CharField(blank=True, max_length=24)),
                ("to_status", models.CharField(blank=True, max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="leads.sitelead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
