# Generated by Django 5.2.16 on 2026-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitelead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Novo"),
                    ("in_analysis", "Em análise"),
                    ("contacted", "Cliente contatado"),
                    ("awaiting_return", "Aguardando retorno"),
                    ("converted_customer", "Convertido em cliente"),
                    ("converted_appointment", "Convertido em agendamento"),
                    ("converted_os", "Convertido em OS"),
                    ("converted_quote", "Convertido em orçamento"),
                    ("duplicate", "Duplicado"),
                    ("no_success", "Sem sucesso"),
                    ("canceled", "Cancelado"),
                ],
                db_index=True,
                default="new",
                max_length=24,
            ),
        ),
    ]
