# Generated by Django 5.2.16 on 2026-07-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_alter_sitelead_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadsettings",
            name="allow_create_appointment",
        ),
    ]
