# Generated by Django 5.2.16 on 2026-07-09 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0003_customer_is_active_customer_uniq_customer_phone_and_more"),
        ("leads", "0003_remove_leadsettings_allow_create_appointment"),
        ("orders", "0008_alter_workorder_is_active_alter_workorder_status"),
        ("quotes", "0004_alter_quote_status"),
        ("vehicles", "0002_alter_vehicle_license_plate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("segment_key", models.CharField(blank=True, max_length=40)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "E-mail"),
                            ("phone", "Ligação"),
                            ("none", "—"),
                        ],
                        default="whatsapp",
                        max_length=12,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("approved", "Aprovada"),
                            ("sent", "Enviada"),
                            ("canceled", "Cancelada"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("audience_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CrmSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("tone", models.CharField(default="cordial", max_length=20)),
                (
                    "global_prompt",
                    models.TextField(
                        default="Você é um assistente de CRM para uma oficina mecânica. Sua função é sugerir ações de relacionamento com clientes com base em dados reais do sistema, como status da OS, orçamento, histórico de atendimento, prazos e campanhas sazonais.\n\nNunca invente informações. Nunca prometa desconto, prazo, diagnóstico, garantia ou serviço que não esteja registrado. Nunca use tom alarmista ou pressão excessiva. Sugira ações úteis, éticas e profissionais.\n\nQuando gerar mensagens para clientes, use linguagem clara, cordial e objetiva. A mensagem deve ser revisada por um usuário da oficina antes do envio. Não exponha observações internas, dados sensíveis ou informações financeiras sem autorização."
                    ),
                ),
                ("allow_ai_messages", models.BooleanField(default=True)),
                ("use_os_data", models.BooleanField(default=True)),
                ("use_financial_data", models.BooleanField(default=False)),
                ("auto_send_messages", models.BooleanField(default=False)),
                ("auto_create_tasks", models.BooleanField(default=False)),
                ("seasonal_campaigns_enabled", models.BooleanField(default=True)),
                ("daily_limit", models.PositiveIntegerField(default=100)),
                ("lead_sla_hours", models.PositiveIntegerField(default=4)),
                ("quote_followup_days", models.PositiveIntegerField(default=2)),
                ("quote_expiring_days", models.PositiveIntegerField(default=2)),
                ("rejected_recovery_days", models.PositiveIntegerField(default=7)),
                ("os_ready_days", models.PositiveIntegerField(default=1)),
                ("os_awaiting_days", models.PositiveIntegerField(default=2)),
                ("os_stalled_days", models.PositiveIntegerField(default=3)),
                ("post_service_days", models.PositiveIntegerField(default=2)),
                ("preventive_months", models.PositiveIntegerField(default=6)),
                ("inactive_months", models.PositiveIntegerField(default=6)),
                ("holiday_lead_days", models.PositiveIntegerField(default=15)),
                ("active_types", models.JSONField(blank=True, default=list)),
                ("custom_holidays", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CrmSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("quote_followup", "Follow-up de orçamento"),
                            ("quote_rejected", "Recuperação de orçamento recusado"),
                            ("quote_expiring", "Orçamento perto de expirar"),
                            ("os_ready", "OS pronta para retirada"),
                            ("os_awaiting_approval", "OS aguardando aprovação"),
                            ("os_stalled", "OS parada no status"),
                            ("post_service", "Pós-serviço"),
                            ("preventive", "Revisão preventiva"),
                            ("inactive_customer", "Cliente inativo"),
                            ("lead_followup", "Follow-up de pedido do site"),
                            ("seasonal_campaign", "Campanha sazonal"),
                            ("manual", "Sugestão manual"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("conversation", "Follow-up de conversa"),
                            ("quote", "Orçamento"),
                            ("order", "Ordem de Serviço"),
                            ("reactivation", "Reativação"),
                            ("campaign", "Campanha"),
                            ("opportunity", "Oportunidade por histórico"),
                            ("post_service", "Pós-serviço"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nova"),
                            ("in_analysis", "Em análise"),
                            ("scheduled", "Agendada"),
                            ("in_progress", "Em andamento"),
                            ("sent", "Enviada"),
                            ("completed", "Concluída"),
                            ("ignored", "Ignorada"),
                            ("snoozed", "Adiada"),
                            ("expired", "Expirada"),
                            ("canceled", "Cancelada"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=300)),
                ("recommended_action", models.CharField(max_length=200)),
                ("suggested_text", models.TextField(blank=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "E-mail"),
                            ("phone", "Ligação"),
                            ("none", "—"),
                        ],
                        default="whatsapp",
                        max_length=12,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("snoozed_until", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("rule", "Regra"), ("ai", "IA"), ("manual", "Manual")],
                        default="rule",
                        max_length=10,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "dedup_key",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_suggestions",
                        to="customers.customer",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="leads.sitelead",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="quotes.quote",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CrmSuggestionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="crm.crmsuggestion",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="CrmTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberta"),
                            ("done", "Concluída"),
                            ("canceled", "Cancelada"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_tasks",
                        to="customers.customer",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="quotes.quote",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="crm.crmsuggestion",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="crmsuggestion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedup_key", ""), _negated=True),
                fields=("dedup_key",),
                name="uniq_crm_suggestion_dedup",
            ),
        ),
    ]
