# Generated by Django 5.2.15 on 2026-07-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Pessoa Física"),
                            ("company", "Pessoa Jurídica"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=11)),
                ("document", models.CharField(blank=True, max_length=14)),
                ("zip_code", models.CharField(blank=True, max_length=8)),
                ("street", models.CharField(blank=True, max_length=200)),
                ("number", models.CharField(blank=True, max_length=20)),
                ("complement", models.CharField(blank=True, max_length=100)),
                ("neighborhood", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                (
                    "country",
                    models.CharField(blank=True, default="Brasil", max_length=60),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
