# Generated by Django 5.2.15 on 2026-07-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
