# Generated by Django 5.2.16 on 2026-07-09 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_is_active_customer_uniq_customer_phone_and_more"),
        ("orders", "0008_alter_workorder_is_active_alter_workorder_status"),
        ("quotes", "0004_alter_quote_status"),
        ("vehicles", "0002_alter_vehicle_license_plate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "Ligação"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "E-mail"),
                            ("in_person", "Atendimento presencial"),
                            ("site_lead", "Pedido do site"),
                            ("follow_up", "Follow-up"),
                            ("campaign", "Campanha"),
                            ("complaint", "Reclamação"),
                            ("praise", "Elogio"),
                            ("note", "Observação interna"),
                            ("return", "Retorno combinado"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("channel", models.CharField(blank=True, max_length=20)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("summary", models.CharField(max_length=300)),
                ("content", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberta"),
                            ("resolved", "Resolvida"),
                            ("awaiting", "Aguardando retorno"),
                            ("no_success", "Sem sucesso"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("next_action", models.CharField(blank=True, max_length=200)),
                ("next_action_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="customers.customer",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="quotes.quote",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
