"""Catálogo realista de oficina mecânica: os 100 serviços mais realizados no
Brasil (contexto São José dos Campos), com suas peças padrão (obrigatórias ou
opcionais) e combos (pacotes de serviços).

NÃO cria clientes, fornecedores nem Ordens de Serviço -- só o catálogo. É
re-executável: categorias/peças/serviços/pacotes são feitos por upsert (nome),
e as peças padrão de cada serviço e os itens de cada pacote são reconstruídos a
cada execução para refletir estes dados.

    docker compose exec backend python manage.py seed_service_catalog

Dados fictícios (nomes/preços aproximados em BRL) para desenvolvimento e
homologação; ajuste livremente depois.
"""

from decimal import Decimal

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from apps.categories.models import Category
from apps.parts.models import Part
from apps.services.models import (
    PackageService,
    Service,
    ServicePackage,
    ServicePart,
)


def money(value):
    return Decimal(str(value))


def first_or_create(model, lookup, defaults=None):
    """Como get_or_create, mas tolerante a duplicatas pré-existentes num banco
    de desenvolvimento (ex.: duas categorias com o mesmo nome) -- devolve a
    primeira que casar."""
    obj = model.objects.filter(**lookup).first()
    if obj is None:
        obj = model.objects.create(**{**lookup, **(defaults or {})})
    return obj


PART_CATEGORIES = [
    "Filtros",
    "Lubrificantes",
    "Fluidos",
    "Freios",
    "Suspensão",
    "Direção",
    "Arrefecimento",
    "Ignição",
    "Correias",
    "Elétrica",
    "Motor",
    "Câmbio e Embreagem",
    "Ar-condicionado",
    "Escapamento",
    "Injeção e Combustível",
    "Rolamentos",
    "Pneus",
    "Insumos",
]

SERVICE_CATEGORIES = [
    "Revisão preventiva",
    "Troca de óleo",
    "Freios",
    "Suspensão",
    "Direção",
    "Motor",
    "Arrefecimento",
    "Elétrica",
    "Ar-condicionado",
    "Embreagem e câmbio",
    "Escapamento",
    "Injeção e combustível",
    "Alinhamento e balanceamento",
    "Pneus",
    "Diagnóstico",
]

# code, name, brand, part-category, unit, cost, sale, current, min
PARTS = [
    # Filtros
    (
        "FILT-OLEO",
        "Filtro de óleo (linha leve)",
        "Tecfil",
        "Filtros",
        "unit",
        18,
        38,
        20,
        6,
    ),
    ("FILT-AR", "Filtro de ar do motor", "Wega", "Filtros", "unit", 25, 55, 15, 5),
    (
        "FILT-CABINE",
        "Filtro de cabine (ar-condicionado)",
        "Tecfil",
        "Filtros",
        "unit",
        22,
        50,
        15,
        5,
    ),
    ("FILT-COMB", "Filtro de combustível", "Bosch", "Filtros", "unit", 20, 45, 15, 5),
    (
        "FILTRO-COMB-INTERNO",
        "Filtro interno da bomba de combustível",
        "Bosch",
        "Filtros",
        "unit",
        40,
        90,
        6,
        2,
    ),
    # Lubrificantes
    (
        "OL-5W30",
        "Óleo de motor 5W30 sintético (1L)",
        "Lubrax",
        "Lubrificantes",
        "liter",
        30,
        52,
        60,
        15,
    ),
    (
        "OL-5W40",
        "Óleo de motor 5W40 sintético (1L)",
        "Mobil",
        "Lubrificantes",
        "liter",
        34,
        58,
        40,
        12,
    ),
    (
        "OL-15W40",
        "Óleo de motor 15W40 semissintético (1L)",
        "Ipiranga",
        "Lubrificantes",
        "liter",
        22,
        40,
        30,
        10,
    ),
    (
        "OL-CAMBIO-MAN",
        "Óleo de câmbio manual 75W90 (1L)",
        "Valvoline",
        "Lubrificantes",
        "liter",
        35,
        65,
        20,
        6,
    ),
    (
        "OL-CAMBIO-AUT",
        "Óleo de câmbio automático ATF (1L)",
        "Mobil",
        "Lubrificantes",
        "liter",
        40,
        75,
        20,
        6,
    ),
    (
        "OL-DIFER",
        "Óleo de diferencial 85W140 (1L)",
        "Valvoline",
        "Lubrificantes",
        "liter",
        30,
        58,
        12,
        4,
    ),
    ("GRAXA", "Graxa multiuso", "Molykote", "Lubrificantes", "unit", 12, 28, 20, 6),
    # Fluidos
    (
        "FLU-FREIO-DOT4",
        "Fluido de freio DOT4 (500ml)",
        "Bosch",
        "Fluidos",
        "unit",
        12,
        28,
        30,
        8,
    ),
    (
        "FLU-ARREF",
        "Aditivo de radiador concentrado (1L)",
        "Paraflu",
        "Fluidos",
        "liter",
        22,
        42,
        30,
        10,
    ),
    (
        "FLU-DIR-HID",
        "Fluido de direção hidráulica (500ml)",
        "ATF",
        "Fluidos",
        "unit",
        18,
        38,
        15,
        5,
    ),
    (
        "AGUA-DESM",
        "Água desmineralizada (5L)",
        "Genérico",
        "Fluidos",
        "unit",
        8,
        18,
        20,
        6,
    ),
    # Freios
    (
        "PAST-DIANT",
        "Jogo de pastilhas de freio dianteiras",
        "Fras-le",
        "Freios",
        "set",
        75,
        150,
        12,
        4,
    ),
    (
        "PAST-TRAS",
        "Jogo de pastilhas de freio traseiras",
        "Fras-le",
        "Freios",
        "set",
        70,
        140,
        8,
        3,
    ),
    (
        "DISCO-DIANT",
        "Par de discos de freio dianteiros",
        "Fremax",
        "Freios",
        "pair",
        180,
        330,
        6,
        2,
    ),
    (
        "DISCO-TRAS",
        "Par de discos de freio traseiros",
        "Fremax",
        "Freios",
        "pair",
        170,
        310,
        4,
        2,
    ),
    (
        "LONA-FREIO",
        "Jogo de lonas/sapatas de freio traseiro",
        "Fras-le",
        "Freios",
        "set",
        60,
        120,
        6,
        2,
    ),
    (
        "TAMBOR-FREIO",
        "Par de tambores de freio",
        "Fremax",
        "Freios",
        "pair",
        150,
        290,
        3,
        1,
    ),
    (
        "CIL-MESTRE",
        "Cilindro mestre de freio",
        "Bosch",
        "Freios",
        "unit",
        130,
        250,
        3,
        1,
    ),
    ("CIL-RODA", "Cilindro de roda", "Controil", "Freios", "unit", 45, 95, 6, 2),
    ("FLEX-FREIO", "Flexível de freio", "Cobreq", "Freios", "unit", 25, 55, 8, 3),
    (
        "KIT-REPARO-FREIO-MAO",
        "Kit de reparo do freio de estacionamento",
        "Controil",
        "Freios",
        "kit",
        40,
        90,
        4,
        2,
    ),
    # Suspensão
    (
        "AMORT-DIANT",
        "Par de amortecedores dianteiros",
        "Cofap",
        "Suspensão",
        "pair",
        260,
        480,
        6,
        2,
    ),
    (
        "AMORT-TRAS",
        "Par de amortecedores traseiros",
        "Cofap",
        "Suspensão",
        "pair",
        220,
        420,
        6,
        2,
    ),
    (
        "KIT-BATENTE",
        "Kit batente e coifa do amortecedor",
        "Cofap",
        "Suspensão",
        "kit",
        60,
        130,
        8,
        3,
    ),
    (
        "MOLA-SUSP",
        "Par de molas de suspensão",
        "Fabrini",
        "Suspensão",
        "pair",
        180,
        340,
        4,
        2,
    ),
    ("PIVO", "Pivô de suspensão", "Nakata", "Suspensão", "unit", 55, 120, 8, 3),
    (
        "BANDEJA",
        "Bandeja (braço) de suspensão",
        "Nakata",
        "Suspensão",
        "unit",
        160,
        300,
        4,
        2,
    ),
    ("BIELETA", "Par de bieletas", "Nakata", "Suspensão", "pair", 70, 150, 8, 3),
    (
        "BUCHA-BANDEJA",
        "Bucha da bandeja de suspensão",
        "Sampel",
        "Suspensão",
        "unit",
        35,
        80,
        10,
        4,
    ),
    (
        "COXIM-AMORT",
        "Coxim/rolamento do amortecedor dianteiro",
        "Sampel",
        "Suspensão",
        "unit",
        60,
        130,
        8,
        3,
    ),
    (
        "BARRA-ESTAB",
        "Barra estabilizadora",
        "Nakata",
        "Suspensão",
        "unit",
        140,
        260,
        3,
        1,
    ),
    (
        "BUCHA-ESTAB",
        "Kit de buchas da barra estabilizadora",
        "Sampel",
        "Suspensão",
        "kit",
        30,
        70,
        10,
        4,
    ),
    # Direção
    (
        "TERMINAL-DIR",
        "Par de terminais de direção",
        "Nakata",
        "Direção",
        "pair",
        70,
        150,
        8,
        3,
    ),
    ("BARRA-AXIAL", "Par de barras axiais", "Nakata", "Direção", "pair", 90, 180, 6, 2),
    (
        "COIFA-DIR",
        "Coifa da caixa de direção",
        "Sampel",
        "Direção",
        "unit",
        20,
        50,
        10,
        4,
    ),
    ("CAIXA-DIR", "Caixa de direção", "TRW", "Direção", "unit", 500, 950, 2, 1),
    (
        "BOMBA-DIR-HID",
        "Bomba de direção hidráulica",
        "ZF",
        "Direção",
        "unit",
        350,
        650,
        2,
        1,
    ),
    (
        "JUNTA-HOMOC",
        "Junta homocinética (fixa)",
        "Nakata",
        "Direção",
        "unit",
        120,
        230,
        5,
        2,
    ),
    (
        "COIFA-HOMOC",
        "Kit da coifa da homocinética",
        "Sampel",
        "Direção",
        "kit",
        30,
        70,
        12,
        4,
    ),
    ("SEMIEIXO", "Semieixo completo", "Nakata", "Direção", "unit", 320, 590, 3, 1),
    # Rolamentos
    (
        "ROLAMENTO-DIANT",
        "Rolamento de roda dianteiro",
        "SKF",
        "Rolamentos",
        "unit",
        70,
        150,
        8,
        3,
    ),
    (
        "ROLAMENTO-TRAS",
        "Rolamento de roda traseiro",
        "SKF",
        "Rolamentos",
        "unit",
        65,
        140,
        8,
        3,
    ),
    (
        "CUBO-RODA",
        "Cubo de roda com rolamento",
        "SKF",
        "Rolamentos",
        "unit",
        150,
        290,
        4,
        2,
    ),
    # Arrefecimento
    ("RADIADOR", "Radiador", "Valeo", "Arrefecimento", "unit", 320, 600, 3, 1),
    (
        "VENTOINHA",
        "Eletroventilador (ventoinha) do radiador",
        "Valeo",
        "Arrefecimento",
        "unit",
        260,
        480,
        3,
        1,
    ),
    (
        "MANG-RADIADOR-SUP",
        "Mangueira superior do radiador",
        "Wega",
        "Arrefecimento",
        "unit",
        30,
        70,
        8,
        3,
    ),
    (
        "MANG-RADIADOR-INF",
        "Mangueira inferior do radiador",
        "Wega",
        "Arrefecimento",
        "unit",
        30,
        70,
        8,
        3,
    ),
    (
        "RESERV-EXPANSAO",
        "Reservatório de expansão",
        "Wega",
        "Arrefecimento",
        "unit",
        55,
        120,
        6,
        2,
    ),
    (
        "TAMPA-RADIADOR",
        "Tampa do radiador",
        "Wahler",
        "Arrefecimento",
        "unit",
        20,
        45,
        12,
        4,
    ),
    (
        "VALV-TERMOST",
        "Válvula termostática",
        "Wahler",
        "Arrefecimento",
        "unit",
        40,
        90,
        10,
        4,
    ),
    ("BOMBA-AGUA", "Bomba d'água", "Urba", "Arrefecimento", "unit", 90, 180, 8, 3),
    # Ignição
    (
        "VELA-IGNICAO",
        "Jogo de velas de ignição",
        "NGK",
        "Ignição",
        "set",
        90,
        180,
        12,
        4,
    ),
    (
        "VELA-IRIDIUM",
        "Jogo de velas de ignição Iridium",
        "NGK",
        "Ignição",
        "set",
        160,
        280,
        6,
        2,
    ),
    ("BOBINA-IGN", "Bobina de ignição", "Bosch", "Ignição", "unit", 110, 210, 6, 2),
    ("CABO-VELA", "Jogo de cabos de vela", "NGK", "Ignição", "set", 70, 140, 6, 2),
    # Correias
    (
        "KIT-COR-DENTADA",
        "Kit de correia dentada (correia + tensor)",
        "Gates",
        "Correias",
        "kit",
        200,
        380,
        6,
        2,
    ),
    (
        "KIT-COR-DENTADA-BOMBA",
        "Kit de correia dentada com bomba d'água",
        "Gates",
        "Correias",
        "kit",
        320,
        590,
        4,
        2,
    ),
    (
        "CORREIA-POLYV",
        "Correia do alternador (Poly-V)",
        "Gates",
        "Correias",
        "unit",
        45,
        100,
        10,
        4,
    ),
    (
        "TENSOR-POLYV",
        "Tensor da correia Poly-V",
        "Gates",
        "Correias",
        "unit",
        90,
        180,
        6,
        2,
    ),
    (
        "CORRENTE-COMANDO",
        "Kit de corrente de comando",
        "Iwis",
        "Correias",
        "kit",
        260,
        480,
        2,
        1,
    ),
    # Motor
    ("JUNTA-CABECOTE", "Junta do cabeçote", "Sabó", "Motor", "unit", 90, 190, 4, 2),
    (
        "JOGO-JUNTAS-MOTOR",
        "Jogo de juntas do motor",
        "Sabó",
        "Motor",
        "kit",
        180,
        350,
        3,
        1,
    ),
    (
        "JUNTA-TAMPA-VALV",
        "Junta da tampa de válvulas",
        "Sabó",
        "Motor",
        "unit",
        30,
        70,
        8,
        3,
    ),
    (
        "RETENTOR-VIRAB-DIANT",
        "Retentor dianteiro do virabrequim",
        "Sabó",
        "Motor",
        "unit",
        25,
        60,
        8,
        3,
    ),
    (
        "RETENTOR-VIRAB-TRAS",
        "Retentor traseiro do virabrequim",
        "Sabó",
        "Motor",
        "unit",
        30,
        70,
        6,
        2,
    ),
    (
        "TUCHO",
        "Jogo de tuchos hidráulicos",
        "Riosulense",
        "Motor",
        "set",
        180,
        340,
        3,
        1,
    ),
    ("COXIM-MOTOR", "Coxim do motor", "Axios", "Motor", "unit", 80, 160, 6, 2),
    ("COXIM-CAMBIO", "Coxim do câmbio", "Axios", "Motor", "unit", 75, 150, 6, 2),
    ("SONDA-LAMBDA", "Sonda lambda", "Bosch", "Motor", "unit", 180, 340, 5, 2),
    # Elétrica
    ("BATERIA-60", "Bateria 60Ah", "Moura", "Elétrica", "unit", 320, 520, 10, 3),
    ("ALTERNADOR", "Alternador", "Bosch", "Elétrica", "unit", 380, 700, 3, 1),
    (
        "MOTOR-PARTIDA",
        "Motor de partida (arranque)",
        "Bosch",
        "Elétrica",
        "unit",
        320,
        600,
        3,
        1,
    ),
    (
        "LAMPADA-FAROL",
        "Par de lâmpadas de farol",
        "Osram",
        "Elétrica",
        "pair",
        25,
        60,
        20,
        6,
    ),
    ("SENSOR-ROTACAO", "Sensor de rotação", "Bosch", "Elétrica", "unit", 70, 150, 6, 2),
    ("SENSOR-MAP", "Sensor MAP", "Bosch", "Elétrica", "unit", 90, 180, 6, 2),
    (
        "MOTOR-VIDRO",
        "Motor do vidro elétrico",
        "Bosch",
        "Elétrica",
        "unit",
        110,
        220,
        4,
        2,
    ),
    ("FUSIVEL-KIT", "Kit de fusíveis e relés", "DNI", "Elétrica", "kit", 15, 40, 20, 6),
    # Ar-condicionado
    (
        "GAS-R134A",
        "Gás R134a (carga)",
        "Genérico",
        "Ar-condicionado",
        "unit",
        60,
        130,
        20,
        6,
    ),
    (
        "FILTRO-SECADOR-AC",
        "Filtro secador do ar-condicionado",
        "Denso",
        "Ar-condicionado",
        "unit",
        45,
        100,
        6,
        2,
    ),
    (
        "HIGIEN-AC",
        "Produto higienizador do ar-condicionado",
        "Wurth",
        "Ar-condicionado",
        "unit",
        20,
        50,
        20,
        6,
    ),
    (
        "COMPRESSOR-AC",
        "Compressor do ar-condicionado",
        "Denso",
        "Ar-condicionado",
        "unit",
        700,
        1300,
        2,
        1,
    ),
    # Câmbio e Embreagem
    (
        "KIT-EMBREAGEM",
        "Kit de embreagem (platô, disco e rolamento)",
        "Luk",
        "Câmbio e Embreagem",
        "kit",
        380,
        700,
        4,
        2,
    ),
    (
        "ATUADOR-EMBREAGEM",
        "Cilindro/atuador da embreagem",
        "Luk",
        "Câmbio e Embreagem",
        "unit",
        90,
        190,
        5,
        2,
    ),
    # Escapamento
    ("CATALISADOR", "Catalisador", "Umicore", "Escapamento", "unit", 350, 650, 3, 1),
    (
        "SILENCIOSO",
        "Silencioso traseiro",
        "Tuper",
        "Escapamento",
        "unit",
        150,
        290,
        4,
        2,
    ),
    (
        "ABRAC-ESCAPE",
        "Kit de abraçadeiras e juntas do escapamento",
        "Tuper",
        "Escapamento",
        "kit",
        25,
        60,
        12,
        4,
    ),
    # Injeção e Combustível
    (
        "BOMBA-COMB",
        "Bomba de combustível",
        "Bosch",
        "Injeção e Combustível",
        "unit",
        220,
        420,
        4,
        2,
    ),
    (
        "LIMP-BICO",
        "Produto para limpeza de bicos e válvulas",
        "Wynn's",
        "Injeção e Combustível",
        "unit",
        25,
        55,
        20,
        6,
    ),
    # Pneus / Insumos
    (
        "PNEU-ARO15",
        "Pneu aro 15 (175/65 R15)",
        "Pirelli",
        "Pneus",
        "unit",
        250,
        420,
        16,
        4,
    ),
    ("VALVULA-PNEU", "Válvula de pneu", "Genérico", "Pneus", "unit", 2, 6, 100, 20),
    (
        "REMENDO-PNEU",
        "Kit de reparo/remendo de pneu",
        "Vipal",
        "Insumos",
        "kit",
        5,
        15,
        50,
        10,
    ),
    (
        "CHUMBO-BAL",
        "Kit de contrapesos de balanceamento",
        "Genérico",
        "Insumos",
        "kit",
        3,
        10,
        100,
        20,
    ),
]

# name, service-category, description, labor_cost, estimated_minutes,
# [(part_code, qty, is_required)]
SERVICES = [
    # --- Revisão preventiva -------------------------------------------------
    (
        "Revisão preventiva 10.000 km",
        "Revisão preventiva",
        "Troca de óleo e filtro, checagem de níveis, freios, pneus, suspensão e itens de segurança.",
        220,
        90,
        [
            ("OL-5W30", 4, True),
            ("FILT-OLEO", 1, True),
            ("FILT-AR", 1, False),
            ("FILT-CABINE", 1, False),
        ],
    ),
    (
        "Revisão preventiva 20.000 km",
        "Revisão preventiva",
        "Revisão intermediária com óleo, filtros e inspeção ampliada de freios, suspensão e arrefecimento.",
        320,
        150,
        [
            ("OL-5W30", 4, True),
            ("FILT-OLEO", 1, True),
            ("FILT-AR", 1, True),
            ("FILT-CABINE", 1, True),
            ("FILT-COMB", 1, False),
        ],
    ),
    (
        "Revisão preventiva completa 40.000 km",
        "Revisão preventiva",
        "Revisão ampla: óleo, todos os filtros, velas, fluido de freio e verificação geral do veículo.",
        480,
        240,
        [
            ("OL-5W30", 4, True),
            ("FILT-OLEO", 1, True),
            ("FILT-AR", 1, True),
            ("FILT-CABINE", 1, True),
            ("FILT-COMB", 1, True),
            ("VELA-IGNICAO", 1, False),
            ("FLU-FREIO-DOT4", 2, False),
        ],
    ),
    (
        "Inspeção pré-viagem (checklist)",
        "Revisão preventiva",
        "Checklist completo de segurança para viagem: freios, pneus, suspensão, iluminação, fluidos e correias.",
        120,
        60,
        [],
    ),
    (
        "Troca do filtro de ar do motor",
        "Revisão preventiva",
        "Substituição do filtro de ar do motor.",
        40,
        20,
        [("FILT-AR", 1, True)],
    ),
    (
        "Troca do filtro de cabine (ar-condicionado)",
        "Revisão preventiva",
        "Substituição do filtro de cabine/pólen do sistema de ventilação.",
        50,
        25,
        [("FILT-CABINE", 1, True)],
    ),
    (
        "Troca do filtro de combustível",
        "Revisão preventiva",
        "Substituição do filtro de combustível.",
        70,
        40,
        [("FILT-COMB", 1, True)],
    ),
    # --- Troca de óleo ------------------------------------------------------
    (
        "Troca de óleo e filtro (sintético 5W30)",
        "Troca de óleo",
        "Drenagem do óleo usado, troca do filtro de óleo e reposição com óleo sintético 5W30.",
        90,
        40,
        [("OL-5W30", 4, True), ("FILT-OLEO", 1, True)],
    ),
    (
        "Troca de óleo e filtro (sintético 5W40)",
        "Troca de óleo",
        "Drenagem do óleo usado, troca do filtro e reposição com óleo sintético 5W40.",
        90,
        40,
        [("OL-5W40", 4, True), ("FILT-OLEO", 1, True)],
    ),
    (
        "Troca de óleo e filtro (semissintético 15W40)",
        "Troca de óleo",
        "Drenagem do óleo usado, troca do filtro e reposição com óleo semissintético 15W40.",
        80,
        40,
        [("OL-15W40", 4, True), ("FILT-OLEO", 1, True)],
    ),
    (
        "Troca de óleo do câmbio manual",
        "Troca de óleo",
        "Drenagem e reposição do óleo da caixa de câmbio manual.",
        90,
        45,
        [("OL-CAMBIO-MAN", 2, True)],
    ),
    (
        "Troca de óleo do câmbio automático",
        "Troca de óleo",
        "Drenagem e reposição do óleo (ATF) do câmbio automático.",
        180,
        90,
        [("OL-CAMBIO-AUT", 6, True), ("FILT-OLEO", 1, False)],
    ),
    (
        "Troca de óleo do diferencial",
        "Troca de óleo",
        "Drenagem e reposição do óleo do diferencial.",
        80,
        40,
        [("OL-DIFER", 2, True)],
    ),
    (
        "Lubrificação geral do chassi",
        "Troca de óleo",
        "Lubrificação de articulações, dobradiças e pontos do chassi com graxa.",
        60,
        30,
        [("GRAXA", 1, True)],
    ),
    # --- Freios -------------------------------------------------------------
    (
        "Troca de pastilhas de freio dianteiras",
        "Freios",
        "Substituição do jogo de pastilhas dianteiras, limpeza dos componentes e teste de frenagem.",
        140,
        60,
        [("PAST-DIANT", 1, True), ("FLU-FREIO-DOT4", 1, False)],
    ),
    (
        "Troca de pastilhas de freio traseiras",
        "Freios",
        "Substituição do jogo de pastilhas traseiras e teste de frenagem.",
        130,
        60,
        [("PAST-TRAS", 1, True)],
    ),
    (
        "Troca de discos de freio dianteiros",
        "Freios",
        "Substituição do par de discos dianteiros; recomenda-se trocar as pastilhas junto.",
        160,
        70,
        [("DISCO-DIANT", 1, True), ("PAST-DIANT", 1, False)],
    ),
    (
        "Troca de discos de freio traseiros",
        "Freios",
        "Substituição do par de discos traseiros.",
        150,
        70,
        [("DISCO-TRAS", 1, True), ("PAST-TRAS", 1, False)],
    ),
    (
        "Troca de pastilhas e discos dianteiros",
        "Freios",
        "Substituição conjunta de pastilhas e discos dianteiros, com verificação do fluido.",
        220,
        100,
        [
            ("PAST-DIANT", 1, True),
            ("DISCO-DIANT", 1, True),
            ("FLU-FREIO-DOT4", 1, False),
        ],
    ),
    (
        "Troca de lonas/sapatas de freio (traseiro)",
        "Freios",
        "Substituição das lonas/sapatas do freio a tambor traseiro.",
        150,
        80,
        [("LONA-FREIO", 1, True)],
    ),
    (
        "Troca de tambor de freio",
        "Freios",
        "Substituição do par de tambores de freio traseiros.",
        150,
        80,
        [("TAMBOR-FREIO", 1, True), ("LONA-FREIO", 1, False)],
    ),
    (
        "Sangria (purga) do sistema de freios",
        "Freios",
        "Sangria completa do sistema de freios, com reposição do fluido.",
        120,
        60,
        [("FLU-FREIO-DOT4", 2, True)],
    ),
    (
        "Troca do fluido de freio (DOT4)",
        "Freios",
        "Substituição total do fluido de freio por DOT4 novo.",
        120,
        60,
        [("FLU-FREIO-DOT4", 2, True)],
    ),
    (
        "Troca do cilindro mestre de freio",
        "Freios",
        "Substituição do cilindro mestre e sangria do sistema.",
        220,
        120,
        [("CIL-MESTRE", 1, True), ("FLU-FREIO-DOT4", 2, False)],
    ),
    (
        "Troca do cilindro de roda",
        "Freios",
        "Substituição do cilindro de roda e sangria do circuito.",
        130,
        70,
        [("CIL-RODA", 1, True), ("FLU-FREIO-DOT4", 1, False)],
    ),
    (
        "Troca do flexível de freio",
        "Freios",
        "Substituição da mangueira flexível de freio e sangria.",
        110,
        60,
        [("FLEX-FREIO", 1, True), ("FLU-FREIO-DOT4", 1, False)],
    ),
    (
        "Reparo do freio de estacionamento",
        "Freios",
        "Regulagem/reparo do freio de mão com substituição do kit de reparo.",
        120,
        60,
        [("KIT-REPARO-FREIO-MAO", 1, True)],
    ),
    # --- Suspensão ----------------------------------------------------------
    (
        "Troca de amortecedores dianteiros",
        "Suspensão",
        "Substituição do par de amortecedores dianteiros; recomenda-se kit batente junto.",
        240,
        120,
        [
            ("AMORT-DIANT", 1, True),
            ("KIT-BATENTE", 1, False),
            ("COXIM-AMORT", 2, False),
        ],
    ),
    (
        "Troca de amortecedores traseiros",
        "Suspensão",
        "Substituição do par de amortecedores traseiros.",
        220,
        110,
        [("AMORT-TRAS", 1, True), ("KIT-BATENTE", 1, False)],
    ),
    (
        "Troca do kit batente e coifa do amortecedor",
        "Suspensão",
        "Substituição dos batentes e coifas dos amortecedores.",
        140,
        80,
        [("KIT-BATENTE", 1, True)],
    ),
    (
        "Troca de molas de suspensão",
        "Suspensão",
        "Substituição do par de molas de suspensão.",
        220,
        120,
        [("MOLA-SUSP", 1, True)],
    ),
    (
        "Troca de pivô de suspensão",
        "Suspensão",
        "Substituição do pivô de suspensão, com alinhamento após o serviço.",
        130,
        70,
        [("PIVO", 1, True)],
    ),
    (
        "Troca da bandeja (braço) de suspensão",
        "Suspensão",
        "Substituição da bandeja de suspensão, incluindo pivô e buchas quando necessário.",
        220,
        120,
        [("BANDEJA", 1, True), ("PIVO", 1, False), ("BUCHA-BANDEJA", 2, False)],
    ),
    (
        "Troca de bieletas",
        "Suspensão",
        "Substituição do par de bieletas da suspensão.",
        90,
        45,
        [("BIELETA", 1, True)],
    ),
    (
        "Troca de buchas da bandeja",
        "Suspensão",
        "Substituição das buchas da bandeja de suspensão.",
        160,
        90,
        [("BUCHA-BANDEJA", 2, True)],
    ),
    (
        "Troca do coxim/rolamento do amortecedor",
        "Suspensão",
        "Substituição do coxim e rolamento superior do amortecedor.",
        140,
        70,
        [("COXIM-AMORT", 2, True)],
    ),
    (
        "Troca da barra estabilizadora",
        "Suspensão",
        "Substituição da barra estabilizadora e buchas.",
        180,
        90,
        [("BARRA-ESTAB", 1, True), ("BUCHA-ESTAB", 1, False)],
    ),
    (
        "Troca das buchas da barra estabilizadora",
        "Suspensão",
        "Substituição das buchas da barra estabilizadora.",
        110,
        60,
        [("BUCHA-ESTAB", 1, True)],
    ),
    (
        "Troca do rolamento de roda dianteiro",
        "Suspensão",
        "Substituição do rolamento de roda dianteiro.",
        180,
        90,
        [("ROLAMENTO-DIANT", 1, True)],
    ),
    (
        "Troca do rolamento de roda traseiro",
        "Suspensão",
        "Substituição do rolamento de roda traseiro.",
        160,
        80,
        [("ROLAMENTO-TRAS", 1, True)],
    ),
    (
        "Troca do cubo de roda",
        "Suspensão",
        "Substituição do cubo de roda com rolamento.",
        200,
        100,
        [("CUBO-RODA", 1, True)],
    ),
    # --- Direção ------------------------------------------------------------
    (
        "Troca de terminais de direção",
        "Direção",
        "Substituição do par de terminais de direção, com alinhamento após o serviço.",
        120,
        60,
        [("TERMINAL-DIR", 1, True)],
    ),
    (
        "Troca das barras axiais",
        "Direção",
        "Substituição do par de barras axiais, com alinhamento após o serviço.",
        160,
        80,
        [("BARRA-AXIAL", 1, True)],
    ),
    (
        "Troca da coifa da caixa de direção",
        "Direção",
        "Substituição da coifa da caixa de direção.",
        120,
        70,
        [("COIFA-DIR", 1, True)],
    ),
    (
        "Troca da caixa de direção",
        "Direção",
        "Substituição da caixa de direção, com sangria e alinhamento.",
        380,
        180,
        [("CAIXA-DIR", 1, True), ("FLU-DIR-HID", 1, False)],
    ),
    (
        "Troca da bomba de direção hidráulica",
        "Direção",
        "Substituição da bomba de direção hidráulica e do fluido.",
        320,
        150,
        [("BOMBA-DIR-HID", 1, True), ("FLU-DIR-HID", 1, False)],
    ),
    (
        "Troca do fluido de direção hidráulica",
        "Direção",
        "Substituição do fluido do sistema de direção hidráulica.",
        90,
        45,
        [("FLU-DIR-HID", 1, True)],
    ),
    (
        "Troca da junta homocinética",
        "Direção",
        "Substituição da junta homocinética fixa e coifa.",
        200,
        100,
        [("JUNTA-HOMOC", 1, True), ("COIFA-HOMOC", 1, False)],
    ),
    (
        "Troca da coifa da homocinética",
        "Direção",
        "Substituição da coifa da junta homocinética.",
        140,
        80,
        [("COIFA-HOMOC", 1, True)],
    ),
    (
        "Troca do semieixo",
        "Direção",
        "Substituição do semieixo completo.",
        220,
        110,
        [("SEMIEIXO", 1, True)],
    ),
    # --- Alinhamento e balanceamento ---------------------------------------
    (
        "Alinhamento de direção (computadorizado)",
        "Alinhamento e balanceamento",
        "Alinhamento computadorizado da geometria da direção.",
        90,
        40,
        [],
    ),
    (
        "Balanceamento de rodas",
        "Alinhamento e balanceamento",
        "Balanceamento das quatro rodas com contrapesos.",
        80,
        40,
        [("CHUMBO-BAL", 1, True)],
    ),
    (
        "Rodízio de pneus",
        "Alinhamento e balanceamento",
        "Rodízio dos pneus conforme recomendação do fabricante.",
        50,
        30,
        [],
    ),
    # --- Pneus --------------------------------------------------------------
    (
        "Montagem e desmontagem de pneu",
        "Pneus",
        "Desmontagem e montagem de pneu na roda, com verificação da válvula.",
        40,
        25,
        [("VALVULA-PNEU", 1, False)],
    ),
    (
        "Troca de pneu aro 15 (unidade)",
        "Pneus",
        "Fornecimento e montagem de um pneu aro 15, com balanceamento.",
        60,
        30,
        [("PNEU-ARO15", 1, True), ("VALVULA-PNEU", 1, False)],
    ),
    (
        "Conserto de pneu (reparo)",
        "Pneus",
        "Reparo de furo no pneu com remendo/manchão.",
        40,
        25,
        [("REMENDO-PNEU", 1, True)],
    ),
    # --- Motor --------------------------------------------------------------
    (
        "Troca da correia dentada (kit)",
        "Motor",
        "Substituição do kit de correia dentada (correia e tensor) conforme aplicação.",
        420,
        210,
        [("KIT-COR-DENTADA", 1, True), ("FLU-ARREF", 2, False)],
    ),
    (
        "Troca da correia dentada com bomba d'água",
        "Motor",
        "Substituição do kit de correia dentada incluindo a bomba d'água.",
        520,
        240,
        [("KIT-COR-DENTADA-BOMBA", 1, True), ("FLU-ARREF", 2, False)],
    ),
    (
        "Troca da correia do alternador (Poly-V)",
        "Motor",
        "Substituição da correia Poly-V dos acessórios.",
        120,
        60,
        [("CORREIA-POLYV", 1, True), ("TENSOR-POLYV", 1, False)],
    ),
    (
        "Troca do tensor da correia Poly-V",
        "Motor",
        "Substituição do tensor da correia dos acessórios.",
        140,
        70,
        [("TENSOR-POLYV", 1, True), ("CORREIA-POLYV", 1, False)],
    ),
    (
        "Troca da junta do cabeçote",
        "Motor",
        "Substituição da junta do cabeçote, com verificação de planicidade e reposição de fluidos.",
        900,
        480,
        [
            ("JUNTA-CABECOTE", 1, True),
            ("JOGO-JUNTAS-MOTOR", 1, False),
            ("FLU-ARREF", 2, False),
        ],
    ),
    (
        "Retífica/planificação do cabeçote",
        "Motor",
        "Planificação do cabeçote e recondicionamento das válvulas.",
        600,
        360,
        [("JUNTA-CABECOTE", 1, False)],
    ),
    (
        "Troca da bomba d'água",
        "Motor",
        "Substituição da bomba d'água e reposição do fluido de arrefecimento.",
        260,
        150,
        [("BOMBA-AGUA", 1, True), ("FLU-ARREF", 2, False)],
    ),
    (
        "Troca da válvula termostática",
        "Motor",
        "Substituição da válvula termostática e reposição do fluido.",
        140,
        70,
        [("VALV-TERMOST", 1, True), ("FLU-ARREF", 1, False)],
    ),
    (
        "Troca da junta da tampa de válvulas",
        "Motor",
        "Substituição da junta da tampa de válvulas para corrigir vazamento de óleo.",
        160,
        90,
        [("JUNTA-TAMPA-VALV", 1, True)],
    ),
    (
        "Regulagem de válvulas",
        "Motor",
        "Regulagem da folga das válvulas conforme especificação.",
        220,
        120,
        [("JUNTA-TAMPA-VALV", 1, False)],
    ),
    (
        "Troca dos tuchos hidráulicos",
        "Motor",
        "Substituição dos tuchos hidráulicos para eliminar ruído do comando.",
        320,
        180,
        [("TUCHO", 1, True), ("JUNTA-TAMPA-VALV", 1, False)],
    ),
    (
        "Troca da corrente de comando (kit)",
        "Motor",
        "Substituição do kit de corrente de comando (corrente, guias e tensor).",
        700,
        360,
        [("CORRENTE-COMANDO", 1, True), ("JOGO-JUNTAS-MOTOR", 1, False)],
    ),
    (
        "Troca dos coxins do motor",
        "Motor",
        "Substituição dos coxins (calços) do motor.",
        180,
        90,
        [("COXIM-MOTOR", 1, True)],
    ),
    (
        "Troca do coxim do câmbio",
        "Motor",
        "Substituição do coxim do câmbio.",
        160,
        80,
        [("COXIM-CAMBIO", 1, True)],
    ),
    (
        "Troca dos retentores do virabrequim",
        "Motor",
        "Substituição dos retentores do virabrequim para corrigir vazamento.",
        260,
        150,
        [("RETENTOR-VIRAB-DIANT", 1, True), ("RETENTOR-VIRAB-TRAS", 1, False)],
    ),
    (
        "Troca das velas de ignição",
        "Motor",
        "Substituição do jogo de velas de ignição.",
        90,
        45,
        [("VELA-IGNICAO", 1, True)],
    ),
    (
        "Troca das velas de ignição (Iridium)",
        "Motor",
        "Substituição do jogo de velas de ignição de Iridium (longa duração).",
        100,
        45,
        [("VELA-IRIDIUM", 1, True)],
    ),
    (
        "Troca das bobinas de ignição",
        "Motor",
        "Substituição da(s) bobina(s) de ignição.",
        120,
        60,
        [("BOBINA-IGN", 1, True)],
    ),
    (
        "Troca dos cabos de vela",
        "Motor",
        "Substituição do jogo de cabos de vela.",
        80,
        40,
        [("CABO-VELA", 1, True)],
    ),
    (
        "Troca da sonda lambda",
        "Motor",
        "Substituição da sonda lambda e verificação da mistura.",
        160,
        70,
        [("SONDA-LAMBDA", 1, True)],
    ),
    # --- Arrefecimento ------------------------------------------------------
    (
        "Troca do radiador",
        "Arrefecimento",
        "Substituição do radiador e reposição do fluido de arrefecimento.",
        260,
        150,
        [
            ("RADIADOR", 1, True),
            ("FLU-ARREF", 2, False),
            ("MANG-RADIADOR-SUP", 1, False),
        ],
    ),
    (
        "Troca do eletroventilador (ventoinha)",
        "Arrefecimento",
        "Substituição do eletroventilador do radiador.",
        180,
        90,
        [("VENTOINHA", 1, True)],
    ),
    (
        "Troca das mangueiras do radiador",
        "Arrefecimento",
        "Substituição das mangueiras superior e inferior do radiador.",
        140,
        80,
        [("MANG-RADIADOR-SUP", 1, True), ("MANG-RADIADOR-INF", 1, True)],
    ),
    (
        "Troca do reservatório de expansão",
        "Arrefecimento",
        "Substituição do reservatório de expansão.",
        90,
        45,
        [("RESERV-EXPANSAO", 1, True)],
    ),
    (
        "Higienização e troca do fluido de arrefecimento",
        "Arrefecimento",
        "Limpeza do sistema (flush) e reposição do fluido de arrefecimento.",
        160,
        90,
        [("FLU-ARREF", 2, True), ("AGUA-DESM", 2, False)],
    ),
    (
        "Troca da tampa do radiador",
        "Arrefecimento",
        "Substituição da tampa do radiador e teste de pressão.",
        50,
        20,
        [("TAMPA-RADIADOR", 1, True)],
    ),
    # --- Elétrica -----------------------------------------------------------
    (
        "Troca da bateria",
        "Elétrica",
        "Substituição da bateria e verificação do sistema de carga.",
        40,
        20,
        [("BATERIA-60", 1, True)],
    ),
    (
        "Troca do alternador",
        "Elétrica",
        "Substituição do alternador e verificação da correia dos acessórios.",
        260,
        120,
        [("ALTERNADOR", 1, True), ("CORREIA-POLYV", 1, False)],
    ),
    (
        "Troca do motor de partida (arranque)",
        "Elétrica",
        "Substituição do motor de partida.",
        240,
        120,
        [("MOTOR-PARTIDA", 1, True)],
    ),
    (
        "Troca das lâmpadas do farol",
        "Elétrica",
        "Substituição do par de lâmpadas do farol.",
        40,
        20,
        [("LAMPADA-FAROL", 1, True)],
    ),
    (
        "Diagnóstico eletrônico com scanner",
        "Diagnóstico",
        "Leitura de módulos, códigos de falha e parâmetros em tempo real, com apagamento após avaliação.",
        150,
        60,
        [],
    ),
    (
        "Troca do sensor de rotação",
        "Elétrica",
        "Substituição do sensor de rotação do motor.",
        120,
        60,
        [("SENSOR-ROTACAO", 1, True)],
    ),
    (
        "Troca do sensor MAP",
        "Elétrica",
        "Substituição do sensor MAP (pressão do coletor).",
        110,
        50,
        [("SENSOR-MAP", 1, True)],
    ),
    (
        "Troca do motor do vidro elétrico",
        "Elétrica",
        "Substituição do motor do vidro elétrico.",
        140,
        80,
        [("MOTOR-VIDRO", 1, True)],
    ),
    (
        "Reparo elétrico (chicote e fusíveis)",
        "Elétrica",
        "Diagnóstico e reparo de chicote, fusíveis e relés.",
        160,
        90,
        [("FUSIVEL-KIT", 1, False)],
    ),
    # --- Ar-condicionado ----------------------------------------------------
    (
        "Recarga de gás do ar-condicionado",
        "Ar-condicionado",
        "Recarga do gás R134a e teste de estanqueidade do sistema.",
        120,
        60,
        [("GAS-R134A", 1, True), ("FILTRO-SECADOR-AC", 1, False)],
    ),
    (
        "Higienização do ar-condicionado",
        "Ar-condicionado",
        "Higienização do sistema de ar-condicionado e troca do filtro de cabine.",
        120,
        60,
        [("HIGIEN-AC", 1, True), ("FILT-CABINE", 1, False)],
    ),
    (
        "Troca do compressor do ar-condicionado",
        "Ar-condicionado",
        "Substituição do compressor, filtro secador e recarga do gás.",
        600,
        240,
        [
            ("COMPRESSOR-AC", 1, True),
            ("GAS-R134A", 1, False),
            ("FILTRO-SECADOR-AC", 1, False),
        ],
    ),
    # --- Embreagem e câmbio -------------------------------------------------
    (
        "Troca do kit de embreagem",
        "Embreagem e câmbio",
        "Substituição do kit de embreagem (platô, disco e rolamento), com sangria do sistema.",
        600,
        300,
        [
            ("KIT-EMBREAGEM", 1, True),
            ("ATUADOR-EMBREAGEM", 1, False),
            ("OL-CAMBIO-MAN", 2, False),
        ],
    ),
    (
        "Troca do atuador/cilindro da embreagem",
        "Embreagem e câmbio",
        "Substituição do cilindro/atuador da embreagem e sangria.",
        160,
        80,
        [("ATUADOR-EMBREAGEM", 1, True), ("FLU-FREIO-DOT4", 1, False)],
    ),
    # --- Escapamento --------------------------------------------------------
    (
        "Troca do catalisador",
        "Escapamento",
        "Substituição do catalisador do sistema de escape.",
        180,
        90,
        [("CATALISADOR", 1, True), ("ABRAC-ESCAPE", 1, False)],
    ),
    (
        "Troca do silencioso",
        "Escapamento",
        "Substituição do silencioso traseiro do escapamento.",
        140,
        70,
        [("SILENCIOSO", 1, True), ("ABRAC-ESCAPE", 1, False)],
    ),
    # --- Injeção e combustível ---------------------------------------------
    (
        "Limpeza de bicos injetores e corpo de borboleta",
        "Injeção e combustível",
        "Limpeza dos bicos injetores e do corpo de borboleta, com teste de vazão.",
        180,
        90,
        [("LIMP-BICO", 1, True)],
    ),
    (
        "Troca da bomba de combustível",
        "Injeção e combustível",
        "Substituição da bomba de combustível e do filtro interno.",
        260,
        120,
        [("BOMBA-COMB", 1, True), ("FILTRO-COMB-INTERNO", 1, False)],
    ),
]

# name, description, discount_type, discount_value, [service names]
PACKAGES = [
    (
        "Revisão Básica (10.000 km)",
        "Manutenção preventiva simples: óleo, filtro e inspeções rápidas, normalmente a cada 10.000 km.",
        "percent",
        5,
        [
            "Troca de óleo e filtro (sintético 5W30)",
            "Troca do filtro de ar do motor",
            "Troca do filtro de cabine (ar-condicionado)",
        ],
    ),
    (
        "Revisão Intermediária (20.000 km)",
        "Revisão com óleo, filtros e troca de velas, normalmente a cada 20.000 km.",
        "percent",
        8,
        [
            "Troca de óleo e filtro (sintético 5W30)",
            "Troca do filtro de ar do motor",
            "Troca do filtro de cabine (ar-condicionado)",
            "Troca do filtro de combustível",
            "Troca das velas de ignição",
        ],
    ),
    (
        "Revisão Completa (40.000 km)",
        "Revisão ampla com filtros, velas, fluido de freio e higienização do arrefecimento.",
        "percent",
        10,
        [
            "Troca de óleo e filtro (sintético 5W30)",
            "Troca do filtro de ar do motor",
            "Troca do filtro de cabine (ar-condicionado)",
            "Troca do filtro de combustível",
            "Troca das velas de ignição",
            "Troca do fluido de freio (DOT4)",
            "Higienização e troca do fluido de arrefecimento",
        ],
    ),
    (
        "Freio Dianteiro Completo",
        "Indicado para desgaste ou ruído na frenagem dianteira: pastilhas, discos e fluido.",
        "fixed",
        50,
        ["Troca de pastilhas e discos dianteiros", "Troca do fluido de freio (DOT4)"],
    ),
    (
        "Freio Traseiro Completo",
        "Pastilhas e discos traseiros para restaurar a frenagem traseira.",
        "fixed",
        40,
        ["Troca de pastilhas de freio traseiras", "Troca de discos de freio traseiros"],
    ),
    (
        "Freios nas 4 Rodas",
        "Pastilhas dianteiras e traseiras com sangria completa do sistema.",
        "percent",
        8,
        [
            "Troca de pastilhas de freio dianteiras",
            "Troca de pastilhas de freio traseiras",
            "Sangria (purga) do sistema de freios",
        ],
    ),
    (
        "Suspensão Dianteira Completa",
        "Amortecedores, batentes e bieletas dianteiros, com alinhamento.",
        "percent",
        8,
        [
            "Troca de amortecedores dianteiros",
            "Troca do kit batente e coifa do amortecedor",
            "Troca de bieletas",
            "Alinhamento de direção (computadorizado)",
        ],
    ),
    (
        "Kit Direção Segura",
        "Terminais e barras axiais com alinhamento para eliminar folgas na direção.",
        "percent",
        8,
        [
            "Troca de terminais de direção",
            "Troca das barras axiais",
            "Alinhamento de direção (computadorizado)",
        ],
    ),
    (
        "Combo Correia Dentada",
        "Troca da correia dentada com bomba d'água e da correia dos acessórios.",
        "percent",
        7,
        [
            "Troca da correia dentada com bomba d'água",
            "Troca da correia do alternador (Poly-V)",
        ],
    ),
    (
        "Combo Arrefecimento",
        "Bomba d'água, válvula termostática e higienização do sistema de arrefecimento.",
        "percent",
        8,
        [
            "Troca da bomba d'água",
            "Troca da válvula termostática",
            "Higienização e troca do fluido de arrefecimento",
        ],
    ),
    (
        "Alinhamento e Balanceamento",
        "Alinhamento computadorizado e balanceamento das quatro rodas.",
        "fixed",
        20,
        ["Alinhamento de direção (computadorizado)", "Balanceamento de rodas"],
    ),
    (
        "Combo Ar-condicionado",
        "Higienização, recarga de gás e troca do filtro de cabine.",
        "percent",
        10,
        [
            "Higienização do ar-condicionado",
            "Recarga de gás do ar-condicionado",
            "Troca do filtro de cabine (ar-condicionado)",
        ],
    ),
    (
        "Embreagem Completa",
        "Kit de embreagem com atuador e troca do óleo do câmbio.",
        "percent",
        5,
        [
            "Troca do kit de embreagem",
            "Troca do atuador/cilindro da embreagem",
            "Troca de óleo do câmbio manual",
        ],
    ),
    (
        "Pré-viagem Segurança",
        "Checklist, troca de óleo, alinhamento e balanceamento antes de viajar.",
        "percent",
        8,
        [
            "Inspeção pré-viagem (checklist)",
            "Troca de óleo e filtro (sintético 5W30)",
            "Alinhamento de direção (computadorizado)",
            "Balanceamento de rodas",
        ],
    ),
]


class Command(BaseCommand):
    help = (
        "Popula o catálogo com os 100 serviços mais realizados em oficinas "
        "(peças padrão obrigatórias/opcionais) e combos. Não cria cliente, "
        "fornecedor nem OS."
    )

    @transaction.atomic
    def handle(self, *args, **options):
        self._validate()
        cats = self._seed_categories()
        parts = self._seed_parts(cats)
        services = self._seed_services(cats, parts)
        packages = self._seed_packages(services)

        links = ServicePart.objects.filter(service__in=services.values()).count()
        self.stdout.write(
            self.style.SUCCESS(
                "Catálogo populado: "
                f"{len(PART_CATEGORIES) + len(SERVICE_CATEGORIES)} categorias, "
                f"{len(parts)} peças, {len(services)} serviços "
                f"({links} vínculos peça↔serviço) e {len(packages)} combos. "
                "Nenhum cliente, fornecedor ou OS foi criado."
            )
        )

    def _validate(self):
        """Falha cedo se os dados estiverem inconsistentes (código de peça
        inexistente, categoria desconhecida, nome de serviço num combo que não
        existe, ou número de serviços diferente de 100)."""
        if len(SERVICES) != 100:
            raise CommandError(f"Esperados 100 serviços, encontrados {len(SERVICES)}.")

        part_codes = {code for code, *_ in PARTS}
        if len(part_codes) != len(PARTS):
            raise CommandError("Há códigos de peça duplicados em PARTS.")
        part_cats = set(PART_CATEGORIES)
        for code, _n, _b, cat, *_ in PARTS:
            if cat not in part_cats:
                raise CommandError(f"Peça {code}: categoria de peça inválida {cat!r}.")

        service_cats = set(SERVICE_CATEGORIES)
        service_names = set()
        for name, cat, _d, _l, _m, std in SERVICES:
            if name in service_names:
                raise CommandError(f"Serviço duplicado: {name!r}.")
            service_names.add(name)
            if cat not in service_cats:
                raise CommandError(f"Serviço {name!r}: categoria inválida {cat!r}.")
            for code, _qty, _req in std:
                if code not in part_codes:
                    raise CommandError(
                        f"Serviço {name!r} referencia peça inexistente {code!r}."
                    )

        for name, _d, _dt, _dv, svc_names in PACKAGES:
            for svc in svc_names:
                if svc not in service_names:
                    raise CommandError(
                        f"Combo {name!r} referencia serviço inexistente {svc!r}."
                    )

    def _seed_categories(self):
        cats = {"part": {}, "service": {}}
        for name in PART_CATEGORIES:
            cats["part"][name] = first_or_create(
                Category, {"category_type": "part", "name": name}
            )
        for name in SERVICE_CATEGORIES:
            cats["service"][name] = first_or_create(
                Category, {"category_type": "service", "name": name}
            )
        return cats

    def _seed_parts(self, cats):
        parts = {}
        for code, name, brand, cat, unit, cost, sale, cur, minimum in PARTS:
            obj = first_or_create(
                Part,
                {"internal_code": code},
                {
                    "name": name,
                    "brand": brand,
                    "category": cats["part"][cat],
                    "unit_of_measure": unit,
                    "cost_price": money(cost),
                    "sale_price": money(sale),
                    "current_quantity": money(cur),
                    "min_quantity": money(minimum),
                    "is_active": True,
                },
            )
            parts[code] = obj
        return parts

    def _seed_services(self, cats, parts):
        services = {}
        for name, cat, desc, labor, minutes, std in SERVICES:
            obj = first_or_create(
                Service,
                {"name": name},
                {
                    "category": cats["service"][cat],
                    "description": desc,
                    "labor_cost": money(labor),
                    "estimated_minutes": minutes,
                    "is_active": True,
                },
            )
            # Reconstrói as peças padrão para refletir estes dados a cada execução.
            obj.standard_parts.all().delete()
            ServicePart.objects.bulk_create(
                ServicePart(
                    service=obj,
                    part=parts[code],
                    suggested_quantity=money(qty),
                    is_required=required,
                )
                for code, qty, required in std
            )
            services[name] = obj
        return services

    def _seed_packages(self, services):
        packages = {}
        for name, desc, discount_type, discount_value, service_names in PACKAGES:
            obj = first_or_create(
                ServicePackage,
                {"name": name},
                {
                    "description": desc,
                    "discount_type": discount_type,
                    "discount_value": money(discount_value),
                    "is_active": True,
                },
            )
            # Mantém desconto/descrição em dia mesmo se o combo já existia.
            obj.description = desc
            obj.discount_type = discount_type
            obj.discount_value = money(discount_value)
            obj.is_active = True
            obj.save(
                update_fields=[
                    "description",
                    "discount_type",
                    "discount_value",
                    "is_active",
                ]
            )
            obj.items.all().delete()
            PackageService.objects.bulk_create(
                PackageService(package=obj, service=services[n]) for n in service_names
            )
            packages[name] = obj
        return packages
