"""Marcas de carros conhecidas/comercializadas no Brasil.

Lista de referência usada para semear a tabela auxiliar ``VehicleBrand`` (só
sugestões de autocomplete; a marca do veículo continua sendo texto livre).
Cobre marcas atuais e históricas presentes na frota brasileira. Ajuste livre.
"""

VEHICLE_BRANDS = [
    "Agrale",
    "Alfa Romeo",
    "Asia Motors",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "BYD",
    "Cadillac",
    "CAOA Chery",
    "Changan",
    "Chery",
    "Chevrolet",
    "Chrysler",
    "Citroën",
    "Daewoo",
    "Daihatsu",
    "Dodge",
    "Effa",
    "Ferrari",
    "Fiat",
    "Ford",
    "Foton",
    "Geely",
    "GMC",
    "GWM",
    "Gurgel",
    "Haval",
    "Honda",
    "Hummer",
    "Hyundai",
    "Iveco",
    "JAC",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lada",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lifan",
    "Mahindra",
    "Maserati",
    "McLaren",
    "Mercedes-Benz",
    "MG",
    "Mini",
    "Mitsubishi",
    "Nissan",
    "Peugeot",
    "Pontiac",
    "Porsche",
    "Puma",
    "RAM",
    "Renault",
    "Rolls-Royce",
    "Saab",
    "Seat",
    "Shineray",
    "Smart",
    "SsangYong",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Troller",
    "Volkswagen",
    "Volvo",
    "Willys",
]
