# Generated by Django 5.2.15 on 2026-07-03 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0002_category_category_type_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("internal_code", models.CharField(blank=True, max_length=50)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model_application", models.CharField(blank=True, max_length=150)),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("unit", "Unidade"),
                            ("pair", "Par"),
                            ("kit", "Kit"),
                            ("liter", "Litro"),
                            ("milliliter", "Mililitro"),
                            ("meter", "Metro"),
                            ("centimeter", "Centímetro"),
                            ("box", "Caixa"),
                            ("pack", "Pacote"),
                            ("set", "Jogo"),
                            ("other", "Outro"),
                        ],
                        default="unit",
                        max_length=20,
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("supplier", models.CharField(blank=True, max_length=150)),
                ("ncm", models.CharField(blank=True, max_length=8)),
                ("barcode", models.CharField(blank=True, max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parts",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
