# Generated by Django 5.2.15 on 2026-07-04 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        # A plain AlterField can't cast the existing text column (all blank
        # strings in practice) to a bigint FK column -- Postgres has no
        # implicit text->bigint cast. Remove and re-add instead; safe here
        # since every existing row's supplier is blank (never a real value).
        migrations.RemoveField(
            model_name="part",
            name="supplier",
        ),
        migrations.AddField(
            model_name="part",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parts",
                to="suppliers.supplier",
            ),
        ),
    ]
